import { ALL_TEAM_AUDIENCE } from "./audiences";
import type { CurriculumModule, CurriculumProgram } from "./types";

const SOURCE = "hospitality-reset-2026-08";

export const HOSPITALITY_RESET_MODULES = [
  {
    id: "cur-reset-promise-care",
    slug: "promise-care",
    title: "The Promise + Ditch CARE",
    summary: "Turn See It. Own It. Elevate It. into four observable moves every teammate can use.",
    audience: ALL_TEAM_AUDIENCE,
    estimatedMinutes: 14,
    outcomes: [
      "State the Ditch operating promise from memory.",
      "Use CARE to choose the next useful action.",
      "Explain how See It, Own It, and Elevate It map to the guest experience.",
    ],
    tags: ["hospitality-reset", "care", "required"],
    sourceIds: [SOURCE],
    content: [
      {
        type: "principle",
        title: "Our operating promise",
        body: "Every guest leaves feeling seen, cared for, and genuinely glad they chose Ditch.",
        tone: "navy",
      },
      {
        type: "steps",
        title: "Ditch CARE",
        items: [
          "C - Catch the Cue: notice the guest, room, teammate, timing, and next need.",
          "A - Act With Ownership: take the next useful action instead of pointing, waiting, or saying it is not yours.",
          "R - Resolve + Recover: close the loop, communicate early, and repair misses with care.",
          "E - End Strong: verify the result, thank the guest sincerely, and create a clear reason to return.",
        ],
      },
      {
        type: "comparison",
        title: "The operating language",
        leftLabel: "Phrase",
        rightLabel: "Observable behavior",
        rows: [
          { left: "See It", right: "Catch the cue before the need becomes a complaint." },
          { left: "Own It", right: "Act, resolve, or make a named handoff and verify it." },
          { left: "Elevate It", right: "Personalize appropriately and end the moment stronger than it began." },
        ],
      },
      {
        type: "practice",
        title: "Cue-to-action sprint",
        prompt: "For five common guest or teammate cues, name the CARE move and the first observable action within five seconds.",
        successCriteria: ["Names the cue", "Chooses an owned action", "Includes a closed loop", "Avoids guessing or overpromising"],
      },
    ],
    assessment: {
      passingScore: 80,
      retryLimit: 2,
      practicalRequired: true,
      questions: [
        {
          id: "reset-care-1",
          type: "multiple-choice",
          prompt: "A guest is searching the room while you are carrying menus to another table. What is the first CARE move?",
          options: ["Finish every current task before reacting", "Catch the cue and acknowledge the guest", "Point toward their server", "Wait for the guest to ask"],
          correctAnswer: "Catch the cue and acknowledge the guest",
          explanation: "Acknowledge immediately, then act or make a named handoff.",
        },
        {
          id: "reset-care-practical",
          type: "practical",
          prompt: "Respond to an arrival, an empty drink outside your section, and a delayed item using CARE.",
          rubric: ["Catches each cue", "Takes or transfers ownership by name", "Communicates before being chased", "Returns to verify", "Ends with warmth"],
        },
      ],
    },
  },
  {
    id: "cur-reset-baseline-magic",
    slug: "baseline-first-magic-second",
    title: "Baseline First. Magic Second.",
    summary: "Protect reliable fundamentals before adding personalized, one-size-fits-one hospitality.",
    audience: ALL_TEAM_AUDIENCE,
    estimatedMinutes: 16,
    outcomes: [
      "Separate the hospitality baseline from an elevated magic moment.",
      "Protect accuracy, communication, safety, and clean resets under pressure.",
      "Create personalization without sacrificing another guest's baseline.",
    ],
    prerequisites: ["cur-reset-promise-care"],
    tags: ["hospitality-reset", "baseline", "guest-journey", "required"],
    sourceIds: [SOURCE],
    content: [
      {
        type: "standard",
        title: "The governing rule",
        body: "A memorable gesture cannot compensate for an invisible arrival, inaccurate order, unsafe guess, silent delay, dirty station, or unfinished handoff. Reliability earns the right to personalize.",
        tone: "orange",
      },
      {
        type: "comparison",
        title: "Baseline vs. magic",
        leftLabel: "Baseline - every guest",
        rightLabel: "Magic - one size fits one",
        rows: [
          { left: "Immediate acknowledgment and a full greet as soon as guest care allows", right: "Use a remembered preference or occasion to shape the welcome" },
          { left: "Accurate order, honest expectations, current product knowledge", right: "Guide the guest toward a choice that fits their exact mood" },
          { left: "Early updates, specific check-backs, closed handoffs", right: "Remove a friction point before the guest notices it" },
          { left: "Safe allergy and alcohol procedures; clean station and reset", right: "Create an appropriate personal detail after the baseline is protected" },
        ],
      },
      {
        type: "steps",
        title: "Guest journey baseline",
        items: [
          "Acknowledge immediately; a guest may wait during volume but should never feel invisible.",
          "Learn the guest's reason, energy, appetite, pace, and needs.",
          "Guide with one or two useful questions and one confident recommendation.",
          "Communicate delays, 86s, timing, mistakes, and changes before frustration builds.",
          "Check back specifically about temperature, flavor, spice, timing, or the corrected item.",
          "Process payment promptly, thank the guest sincerely, and acknowledge the departure.",
        ],
      },
      {
        type: "scenario",
        title: "Protect the baseline",
        prompt: "A regular wants a long conversation while a new party arrives and a kitchen bell sounds. Prioritize the next three actions and preserve warmth with everyone.",
        successCriteria: ["Acknowledges the arrival", "Answers or names the bell handoff", "Pauses the regular naturally", "Returns to close both loops"],
      },
    ],
    assessment: {
      passingScore: 80,
      retryLimit: 2,
      practicalRequired: true,
      questions: [
        {
          id: "reset-baseline-1",
          type: "true-false",
          prompt: "A personalized guest moment counts as great hospitality even if another arrival remains invisible.",
          correctAnswer: false,
          explanation: "The baseline belongs to every guest before magic is added for one guest.",
        },
        {
          id: "reset-baseline-practical",
          type: "practical",
          prompt: "Run the arrival/bell/regular scenario in under 45 seconds.",
          rubric: ["Chooses guest and food priorities correctly", "Uses a named handoff", "Keeps tone calm", "Closes every loop"],
        },
      ],
    },
  },
  {
    id: "cur-reset-whole-room",
    slug: "whole-room-ownership",
    title: "Every Guest Belongs to All of Us",
    summary: "Build five-foot awareness, team hospitality, urgency, and clean handoffs without confusion or scorekeeping.",
    audience: ALL_TEAM_AUDIENCE,
    estimatedMinutes: 15,
    outcomes: ["Use the five-foot mentality", "Make a named handoff", "Help the room without abandoning the assigned role"],
    prerequisites: ["cur-reset-promise-care"],
    tags: ["hospitality-reset", "ownership", "teamwork", "required"],
    sourceIds: [SOURCE],
    content: [
      {
        type: "standard",
        title: "The ownership rule",
        body: "If you see the need, acknowledge it. If you can solve it, solve it. If you cannot, make a named handoff and close the loop.",
        tone: "green",
      },
      {
        type: "checklist",
        title: "What beats low-priority work",
        items: ["Arrivals and waiting guests", "Food in the pass, kitchen bells, and printed tickets", "Empty drinks and dirty tables", "Safety, spills, and allergy communication", "A teammate approaching failure"],
      },
      {
        type: "comparison",
        title: "Ditch language",
        leftLabel: "Retire this",
        rightLabel: "Use this",
        rows: [
          { left: "That is not my table.", right: "I can help, or I will grab the right person and make sure they come over." },
          { left: "Can someone run this?", right: "Jordan, can you run this to 24? I will take 28." },
          { left: "I told them.", right: "I handed it to Alex, Alex confirmed it, and I checked that it was done." },
        ],
      },
      {
        type: "field-assignment",
        title: "Five-foot floor proof",
        prompt: "During one shift, complete one unrequested teammate assist and repair three things simply because they entered your five feet.",
        successCriteria: ["Help actually reduces friction", "Normal responsibilities remain covered", "Handoffs are named and confirmed", "Manager records specific evidence"],
      },
    ],
    assessment: {
      passingScore: 80,
      retryLimit: 2,
      practicalRequired: true,
      questions: [
        {
          id: "reset-room-1",
          type: "multiple-choice",
          prompt: "A request you cannot personally complete is finished when...",
          options: ["You point toward the right station", "You tell any nearby teammate", "A named owner accepts it and you verify the loop", "The guest stops asking"],
          correctAnswer: "A named owner accepts it and you verify the loop",
        },
        {
          id: "reset-room-practical",
          type: "practical",
          prompt: "Demonstrate a clean handoff for a waiting ticket, a guest request, and a spill.",
          rubric: ["Uses a name and exact action", "Receives confirmation", "Protects urgency and safety", "Returns or verifies completion"],
        },
      ],
    },
  },
  {
    id: "cur-reset-passion-selling",
    slug: "passion-selling",
    title: "Passion Selling: Guide, Do Not Push",
    summary: "Use observation and product knowledge to reduce uncertainty and help a guest choose what fits.",
    audience: ALL_TEAM_AUDIENCE,
    estimatedMinutes: 22,
    outcomes: ["Use the five-step Passion Selling formula", "Ask one useful preference question", "Give a truthful sensory recommendation with a point of view"],
    prerequisites: ["cur-reset-baseline-magic"],
    tags: ["hospitality-reset", "passion-selling", "menu", "required"],
    sourceIds: [SOURCE, "food-menu-supplied", "cocktail-menu-supplied", "bar-manual-2026-08"],
    content: [
      {
        type: "steps",
        title: "Observe > Ask > Interpret > Recommend > Describe",
        items: [
          "Observe: notice appetite, pace, occasion, flavor clues, and how much guidance the guest wants.",
          "Ask: use one or two efficient questions - bright or rich, mild or spicy, citrus or smoky, spirit-forward or zero proof.",
          "Interpret: turn the answer into direction instead of repeating the whole menu.",
          "Recommend: take a position - 'For what you described, I would go with...'.",
          "Describe: use truthful texture, flavor, contrast, fit, and a reason to care.",
        ],
      },
      {
        type: "comparison",
        title: "From order taking to guidance",
        leftLabel: "Avoid",
        rightLabel: "Better",
        rows: [
          { left: "Everything is good.", right: "Tell me what sounds better tonight - bright and lighter or rich and comforting?" },
          { left: "Do you want an appetizer?", right: "Before we get into mains, there are two shareables I would not want you to miss." },
          { left: "Would you like another drink?", right: "I can keep you in this same lane or take you somewhere different - what sounds good?" },
        ],
      },
      {
        type: "menu-reference",
        title: "Current practice set",
        itemIds: ["food-yuca-poppers", "food-taco-jerk-shrimp", "food-lobster-roll", "food-zuma-beach-bowl", "drink-hang-10", "drink-smoke-on-the-bay", "drink-pineapple-basil-smash", "drink-watermelon-cooler"],
        instruction: "Use current descriptions and verified flavor lanes. Do not add ingredients, allergy claims, or availability from memory.",
      },
      {
        type: "practice",
        title: "The twenty-second challenge",
        prompt: "Ask one preference question, recommend one current item, explain why it fits, and set one honest expectation in twenty seconds.",
        successCriteria: ["Learns a real preference", "Takes a clear position", "Uses truthful sensory language", "Avoids pressure and ingredient dumping", "Uses only current source facts"],
      },
    ],
    assessment: {
      passingScore: 80,
      retryLimit: 2,
      practicalRequired: true,
      questions: [
        {
          id: "reset-sell-1",
          type: "multi-select",
          prompt: "Which behaviors belong in Passion Selling?",
          options: ["Ask a useful preference question", "Recommend before learning anything", "Take a point of view", "Describe truthfully", "Push the highest-priced item"],
          correctAnswer: ["Ask a useful preference question", "Take a point of view", "Describe truthfully"],
        },
        {
          id: "reset-sell-practical",
          type: "practical",
          prompt: "Guide three profiles: first-time sharer, guest wanting bright/not sweet, and guest wanting a filling meal.",
          rubric: ["Uses full five-step formula", "Current menu facts only", "Recommendation fits", "Expectation is honest", "Language sounds human"],
        },
      ],
    },
  },
  {
    id: "cur-reset-source-safety",
    slug: "source-discipline-allergy-safety",
    title: "Never Guess: Source Discipline + Safety",
    summary: "Know where current truth lives and stop before an uncertain allergy, recipe, beer, or policy answer becomes guest risk.",
    audience: ALL_TEAM_AUDIENCE,
    estimatedMinutes: 16,
    outcomes: ["Use approved sources instead of memory", "Execute the allergy communication chain", "Identify verification-required and rotating menu content"],
    prerequisites: ["cur-reset-passion-selling"],
    tags: ["hospitality-reset", "safety", "allergy", "source-control", "required"],
    sourceIds: [SOURCE, "bar-manual-2026-08", "allergy-source-current", "beer-source-current"],
    content: [
      {
        type: "standard",
        title: "Accuracy is hospitality",
        body: "If you are unsure, say: 'Let me confirm that so I give you the right answer.' Never guess on allergies, alcohol service, a recipe, or an unfamiliar current product.",
        tone: "warning",
      },
      {
        type: "steps",
        title: "Allergy communication chain",
        items: ["Acknowledge the concern without promising an outcome", "Mark it using the current POS procedure", "Communicate it verbally", "Involve the manager", "Allow the kitchen to confirm what can be prepared safely", "Confirm the approved delivery/handoff"],
      },
      {
        type: "source-control",
        title: "Verification-required content",
        sourceIds: ["allergy-source-current", "bar-manual-2026-08"],
        status: "verification-required",
        body: "Do not certify allergy specifics from menu descriptions. Do not train Ancho Average, Sunburnt Summer, Frozen Paloma, Da Painkiller, Island Rum Punch, or Hibiscus Refresher until the recipe lock is approved. Pink salt, wine-pour, and par conflicts also remain manager verification items.",
      },
      {
        type: "source-control",
        title: "Rotating beer",
        sourceIds: ["beer-source-current"],
        status: "rotating",
        body: "Beer selections change by location and date. Demonstrate how to verify the live POS/posted list; do not memorize a historic fixed list as permanent truth.",
      },
    ],
    assessment: {
      passingScore: 100,
      retryLimit: 3,
      practicalRequired: true,
      criticalMisses: ["Guesses an allergy answer", "Teaches a verification-required recipe", "Promises a dish is safe without the approved chain"],
      questions: [
        {
          id: "reset-source-1",
          type: "multiple-choice",
          prompt: "A guest asks whether a dish is safe for a serious allergy and you remember an ingredient list. What should you do?",
          options: ["Answer from memory", "Read the menu description", "Use the current allergy chain and let the kitchen verify", "Say every dish has cross-contact and stop"],
          correctAnswer: "Use the current allergy chain and let the kitchen verify",
          critical: true,
        },
        {
          id: "reset-source-practical",
          type: "practical",
          prompt: "Handle an allergy question, an unavailable beer question, and a recipe conflict.",
          rubric: ["Uses the right source", "States uncertainty calmly", "Escalates to the correct owner", "Does not invent an answer", "Closes the guest loop"],
          critical: true,
        },
      ],
    },
  },
  {
    id: "cur-reset-last",
    slug: "last-recovery",
    title: "L.A.S.T. Guest Recovery",
    summary: "Repair trust, own the problem, follow up personally, and improve the system behind the miss.",
    audience: ALL_TEAM_AUDIENCE,
    estimatedMinutes: 20,
    outcomes: ["Use Listen, Apologize, Solve, Think", "Keep same-team language", "Follow up and identify the system lesson"],
    prerequisites: ["cur-reset-whole-room"],
    tags: ["hospitality-reset", "recovery", "last", "required"],
    sourceIds: [SOURCE, "leadership-os-1"],
    content: [
      {
        type: "steps",
        title: "L.A.S.T.",
        items: [
          "Listen: hear the complete concern and summarize what the guest actually cares about.",
          "Apologize: acknowledge the experience without excuses, blame, or a defensive 'but'.",
          "Solve: take meaningful action; own the issue until it is solved or physically and verbally transferred.",
          "Think: after the guest is cared for, capture what allowed the miss and how the system should improve.",
        ],
      },
      {
        type: "comparison",
        title: "Same-team recovery language",
        leftLabel: "Avoid",
        rightLabel: "Use",
        rows: [
          { left: "The kitchen messed it up.", right: "We missed that. I am getting it corrected right now." },
          { left: "We are slammed.", right: "Thank you for waiting. I have you, and I am getting an update now." },
          { left: "That is our policy.", right: "Here is what I can do. Let me confirm the best next step with my manager." },
        ],
      },
      {
        type: "script",
        title: "A human recovery",
        setup: "Use the structure without sounding like an acronym.",
        lines: ["You are right to be frustrated.", "Let me take care of this with you.", "I will come back personally to make sure we got it right."],
      },
      {
        type: "practice",
        title: "Recovery reps",
        prompt: "Run a cold item, a long wait, and a correctly made item the guest simply dislikes.",
        successCriteria: ["Listens without interruption", "No blame or excuses", "Solution fits the concern and role boundary", "Follows up", "Names a system lesson"],
      },
    ],
    assessment: {
      passingScore: 85,
      retryLimit: 2,
      practicalRequired: true,
      questions: [
        { id: "reset-last-1", type: "multiple-choice", prompt: "When does the Think step happen?", options: ["Before listening", "While debating the facts", "After the guest is cared for", "Only at the monthly meeting"], correctAnswer: "After the guest is cared for" },
        { id: "reset-last-practical", type: "practical", prompt: "Complete one surprise recovery from first sentence through follow-up and system lesson.", rubric: ["Listens", "Acknowledges", "Owns the solution", "Follows up", "Uses same-team language", "Captures prevention"], critical: true },
      ],
    },
  },
  {
    id: "cur-reset-accountability",
    slug: "professionalism-accountability",
    title: "How We Work Here: Professionalism + Accountability",
    summary: "Make readiness, communication, coachability, checklists, resets, and follow-through observable.",
    audience: ALL_TEAM_AUDIENCE,
    estimatedMinutes: 18,
    outcomes: ["Describe the ready-to-work standard", "Receive coaching with Heard and act", "Explain how performance and schedules connect"],
    prerequisites: ["cur-reset-promise-care"],
    tags: ["hospitality-reset", "accountability", "professionalism", "required"],
    sourceIds: [SOURCE],
    content: [
      {
        type: "checklist",
        title: "Observable operating standards",
        items: [
          "Arrive on time, in uniform, with coffee, food, and personal tasks handled.",
          "Keep phones away and out of guest view unless the MOD approves a specific use.",
          "Use professional language: no profanity, gossip, arguing, sexual or inappropriate conversation, panic, blame, or personal drama.",
          "Check 7shifts before work; a read receipt means the instruction was received and must be followed.",
          "Complete and honestly verify opening, handoff, closing, weekly cleaning, PAR, and sidework sheets.",
          "Count first; cover, label on tape, date, FIFO, and return product to its assigned location.",
          "Leave the complete station ready for the next shift.",
        ],
      },
      {
        type: "script",
        title: "Receive coaching cleanly",
        lines: ["Heard.", "Make the immediate correction.", "If needed after the reset: 'Fixed. Can you show me what you want next time so I hit it consistently?'"],
      },
      {
        type: "callout",
        title: "What accountability means",
        body: "Great behavior is recognized specifically. Misses are redirected in real time. Recurring patterns, false sign-offs, ignored direction, or repeated failure to close loops are documented and coached. Schedules reflect business needs and demonstrated reliability, hospitality, pace, teamwork, knowledge, follow-through, and coachability.",
        tone: "sand",
      },
      {
        type: "field-assignment",
        title: "One-week commitment",
        prompt: "Choose one observable behavior to improve for seven days and capture floor evidence every shift.",
        successCriteria: ["Behavior is specific", "Manager can observe it", "Employee receives coaching without a courtroom", "Evidence shows whether it changed"],
      },
    ],
    assessment: {
      passingScore: 80,
      retryLimit: 2,
      practicalRequired: true,
      questions: [
        { id: "reset-account-1", type: "multiple-choice", prompt: "What is the first response to a valid in-the-moment correction?", options: ["Explain the context", "Point out who else missed", "Heard, then correct it", "Wait until after the shift"], correctAnswer: "Heard, then correct it" },
        { id: "reset-account-practical", type: "practical", prompt: "Receive a station-reset correction, act, and ask one useful clarification after the immediate need is protected.", rubric: ["Acknowledges without defense", "Corrects promptly", "Question improves future execution", "Tone stays professional"] },
      ],
    },
  },
  {
    id: "cur-reset-live-certification",
    slug: "hospitality-reset-live-certification",
    title: "Hospitality Reset: Live Floor Certification",
    summary: "Prove the reset through live behavior, not attendance or vocabulary.",
    audience: ALL_TEAM_AUDIENCE,
    estimatedMinutes: 30,
    outcomes: ["Execute the baseline during live service", "Create one appropriate magic moment", "Receive coaching and improve on a second take"],
    prerequisites: ["cur-reset-promise-care", "cur-reset-baseline-magic", "cur-reset-whole-room", "cur-reset-passion-selling", "cur-reset-source-safety", "cur-reset-last", "cur-reset-accountability"],
    tags: ["hospitality-reset", "certification", "live-observation", "required"],
    sourceIds: [SOURCE, "trainer-os-1"],
    content: [
      {
        type: "outcomes",
        title: "Certification proof",
        items: ["Immediate acknowledgment", "Guest discovery and confident guidance", "Current-source discipline", "Whole-room ownership and clean handoffs", "Early communication and specific check-back", "Professional coaching response", "Strong close"],
      },
      {
        type: "field-assignment",
        title: "Observed service block",
        prompt: "A qualified trainer observes a realistic service block and records specific evidence for every baseline behavior plus one personalized moment.",
        successCriteria: ["No critical safety or integrity miss", "Baseline appears consistently", "Magic does not steal from another guest", "One coached miss improves on the second take", "Trainer records evidence, not personality labels"],
      },
    ],
    assessment: {
      passingScore: 85,
      retryLimit: 0,
      practicalRequired: true,
      criticalMisses: ["Guesses an allergy or responsible-service answer", "Ignores an arrival or safety cue", "Blames another department to a guest", "Falsifies a sign-off"],
      questions: [
        { id: "reset-cert-knowledge", type: "short-answer", prompt: "Teach back CARE, Baseline First. Magic Second., Passion Selling, and L.A.S.T. in your own words.", rubric: ["All frameworks accurate", "Connects each to observable behavior", "No invented policy or menu facts"] },
        { id: "reset-cert-live", type: "practical", prompt: "Complete the observed service block.", rubric: ["Baseline protected", "One-size-fits-one moment", "Ownership", "Source safety", "Coachability", "Strong finish"], critical: true },
      ],
    },
  },
] as const satisfies readonly CurriculumModule[];

export const HOSPITALITY_RESET_PROGRAM = {
  id: "program-hospitality-reset",
  slug: "hospitality-reset",
  title: "The Ditch Hospitality Reset",
  summary: "Every guest. Every shift. Every Ditch.",
  audience: ALL_TEAM_AUDIENCE,
  version: "2.0",
  effectiveDate: "2026-08-23",
  moduleIntervalDays: 1,
  moduleIds: HOSPITALITY_RESET_MODULES.map((module) => module.id),
  completionRule: "sequential",
  certification: {
    knowledgeScore: 85,
    practicalRequired: true,
    liveObservationRequired: true,
    auditDays: [7, 30],
  },
} as const satisfies CurriculumProgram;
