import { LEADERSHIP_AUDIENCE } from "./audiences";
import type { CurriculumModule, CurriculumProgram } from "./types";

type LeadershipWeekDefinition = {
  week: number;
  slug: string;
  title: string;
  summary: string;
  minutes: number;
  outcome: string;
  why: string;
  standard: string;
  great: readonly string[];
  language: readonly string[];
  drill: string;
  floor: string;
  watch: readonly string[];
  certify: readonly string[];
  knowledgePrompt: string;
  knowledgeOptions: readonly string[];
  knowledgeAnswer: string;
};

const WEEK_DEFINITIONS = [
  {
    week: 0,
    slug: "culture-calibration",
    title: "Week 0 - Culture Calibration",
    summary: "Name the culture that actually exists before trying to improve it.",
    minutes: 75,
    outcome: "Score observable behavior rather than intentions, personalities, or the restaurant's best night.",
    why: "Aspirational language cannot repair tolerated behavior. Honest calibration gives leadership one shared starting point.",
    standard: "Use specific floor evidence, agree on the largest gaps, and choose a small number of behaviors to stop tolerating immediately.",
    great: ["Scores include observed examples", "Leaders name three priority gaps", "One behavior to stop and one behavior to celebrate are selected", "The first reset has an owner"],
    language: ["What behavior currently survives here?", "What would a new employee copy after three shifts?"],
    drill: "Compare Culture Audit scores. For every score that differs by more than two points, each leader provides one observed example.",
    floor: "Observe one full shift across standards, accountability, hospitality, team hospitality, ownership, selling, recovery, systems, coaching, and training.",
    watch: ["Inflated scores", "Blame", "Vague labels such as bad attitude", "Treating a system failure as a character flaw"],
    certify: ["Completed audit", "Three priority gaps", "One behavior to stop", "One behavior to celebrate", "Leadership agreement on first reset"],
    knowledgePrompt: "What makes a Culture Audit score usable?",
    knowledgeOptions: ["A leader's general feeling", "An observed example tied to a standard", "The employee's intention", "The restaurant's best shift"],
    knowledgeAnswer: "An observed example tied to a standard",
  },
  {
    week: 1,
    slug: "leadership-identity",
    title: "Week 1 - Leadership Identity",
    summary: "Make leadership behavior the clearest training tool in the building.",
    minutes: 75,
    outcome: "Model before mandating, inspect what you expect, coach what you inspect, and reinforce what improves.",
    why: "The team studies what leaders model, ignore, reinforce, and repeat. A leader is always training.",
    standard: "Be visible, calm, willing to help, quick to own misses, and consistent when the room gets busy.",
    great: ["Leader demonstrates before demanding", "Misses are inspected and coached", "Improvement is recognized specifically", "Leader owns a contradiction quickly"],
    language: ["Watch me once. Run it with me once. Now show me the standard without me.", "What did the team learn from watching me in that moment?"],
    drill: "Replay a leader walking past a miss, then replay it with modeling, coaching, and specific recognition.",
    floor: "For seven shifts, capture one moment when leadership behavior reinforced or contradicted the culture.",
    watch: ["Demanding standards the leader does not follow", "Correction without demonstration", "Administrative hiding", "Vague recognition"],
    certify: ["Seven completed reflections", "One live observation", "Evidence of model, inspect, coach, reinforce"],
    knowledgePrompt: "Which sequence is the leadership standard?",
    knowledgeOptions: ["Mandate, assume, criticize, move on", "Model, inspect, coach, reinforce", "Delegate, disappear, review monthly", "Motivate, celebrate, avoid correction"],
    knowledgeAnswer: "Model, inspect, coach, reinforce",
  },
  {
    week: 2,
    slug: "standards-without-ego",
    title: "Week 2 - Standards Without Ego",
    summary: "Create fast, neutral accountability through the 10 for 10 reset and the no-ego response.",
    minutes: 80,
    outcome: "Anyone may protect the standard. The first response to correction is Heard, followed by action.",
    why: "Small disorder compounds. Emotional correction teaches defense instead of protecting the standard.",
    standard: "Notice drift early, call a neutral reset, join the work, verify completion, recognize the reset, and move on without theater.",
    great: ["10 for 10 lasts roughly 30 seconds", "Anyone can call it", "Leader participates", "Completion is verified and released"],
    language: ["10 for 10, team. Thirty-second reset.", "Beautiful - that is our standard. Let's go.", "Heard. Fixed. Can you show me what you want next time?"],
    drill: "Create five minor station misses. Identify drift, call the reset, participate, recognize completion, and release the team.",
    floor: "Use 10 for 10 only when the environment is drifting and verify that the reset is actually complete.",
    watch: ["Using the phrase as punishment", "Calling it without helping", "Public embarrassment", "Sarcasm", "Courtroom explanations"],
    certify: ["Calls and executes a live reset", "Receives a reset with Heard", "Coaches without creating defensiveness"],
    knowledgePrompt: "What is the purpose of 10 for 10?",
    knowledgeOptions: ["Punish a messy employee", "Create a neutral, fast return to standard", "Replace the closing checklist", "Give the manager a break"],
    knowledgeAnswer: "Create a neutral, fast return to standard",
  },
  {
    week: 3,
    slug: "unconditional-hospitality",
    title: "Week 3 - Unconditional Hospitality",
    summary: "Turn awareness into action for guests and coworkers regardless of mood or pressure.",
    minutes: 75,
    outcome: "Notice what a person needs, make it easier, personalize where possible, and act before they have to ask.",
    why: "Hospitality is felt in small moments of anticipation. When it depends on an easy guest or shift, it is not a standard.",
    standard: "Read the room, remove friction, match the guest's preferred pace, and give teammates unrequested support.",
    great: ["Reads quiet and verbal cues", "Acts before being asked", "Matches pace without disappearing", "Team help is useful and unscored"],
    language: ["What can I make better within the next five feet?", "What can we solve before they ask?"],
    drill: "For five guest scenarios, identify the need, friction, personal detail, and anticipatory action.",
    floor: "Log three anticipated needs, two coworker hospitality moments, and one personalized guest experience.",
    watch: ["Robotic scripts", "Over-talking", "Helping only favorite coworkers", "Missing quiet signals", "Confusing speed with care"],
    certify: ["Three live anticipation examples", "At least one coworker example", "Trainer records the cue and action"],
    knowledgePrompt: "What converts awareness into hospitality?",
    knowledgeOptions: ["A positive attitude alone", "A specific action that improves the moment", "Waiting for a request", "A discount"],
    knowledgeAnswer: "A specific action that improves the moment",
  },
  {
    week: 4,
    slug: "passion-selling-leadership",
    title: "Week 4 - Passion Selling",
    summary: "Teach confident, personal recommendations that increase guest value without pressure.",
    minutes: 85,
    outcome: "Observe, ask, interpret, recommend, and describe; take a position based on the guest rather than reciting the menu.",
    why: "Guests gain value when knowledgeable employees reduce uncertainty. Revenue follows trust, relevance, and genuine enthusiasm.",
    standard: "Ask one useful preference question, recommend with confidence, use contrast, describe the experience, and offer a natural pairing.",
    great: ["Recommendation fits the clue", "Description is sensory and truthful", "Contrast sets expectations", "No ingredient dump or automatic add-on"],
    language: ["For what you just described, I would absolutely send you toward...", "Are you leaning brighter and lighter or richer and more comforting?"],
    drill: "Sell one current item without good, delicious, or amazing and without listing ingredients; explain who would love it and who might not.",
    floor: "Make three preference-based recommendations and record the question, recommendation, and guest response.",
    watch: ["Everything is good", "Ingredient dumping", "Fake enthusiasm", "Automatic add-ons", "Recommending before learning"],
    certify: ["Trains one teammate", "Three successful role plays", "One observed live recommendation", "Uses current menu facts"],
    knowledgePrompt: "What should happen before a recommendation?",
    knowledgeOptions: ["Name the most expensive item", "Ask enough to understand the guest", "List every special", "Promise the guest will love it"],
    knowledgeAnswer: "Ask enough to understand the guest",
  },
  {
    week: 5,
    slug: "guest-recovery",
    title: "Week 5 - Guest Recovery",
    summary: "Use L.A.S.T. to care for the guest and improve the system behind the miss.",
    minutes: 85,
    outcome: "Listen, Apologize, Solve, Think; own the problem until it is solved or physically and verbally transferred.",
    why: "A comp may correct a check, but recovery has to repair trust. The response can become more memorable than the miss.",
    standard: "Listen without defense, acknowledge the experience, offer a meaningful solution, follow up personally, and capture the cause.",
    great: ["No excuses or blame", "Solution fits the concern", "Guest receives a specific follow-up", "System lesson has an owner"],
    language: ["You are right to be frustrated.", "Let me take care of this with you.", "I will come back to make sure we got it right."],
    drill: "Run recovery scenarios and score listening, ownership, solution quality, same-team language, follow-up, and system thinking.",
    floor: "Use the recovery log for every meaningful recovery and complete Think after the guest is cared for.",
    watch: ["Excuses", "Department blame", "Policy shields", "Arguing facts", "Disappearing after the solution", "Compensation without care"],
    certify: ["Three simulated recoveries", "One live or case-based recovery", "Follow-up", "System improvement"],
    knowledgePrompt: "What does L.A.S.T. stand for?",
    knowledgeOptions: ["Listen, Apologize, Solve, Think", "Learn, Ask, Sell, Thank", "Look, Act, Support, Transfer", "Listen, Agree, Stop, Talk"],
    knowledgeAnswer: "Listen, Apologize, Solve, Think",
  },
  {
    week: 6,
    slug: "accountability-coaching",
    title: "Week 6 - Accountability + Coaching",
    summary: "Correct observable behavior without ego, labels, humiliation, or delayed ambiguity.",
    minutes: 85,
    outcome: "Use observation, standard, impact, reset, and confirmation to make the next rep more likely to succeed.",
    why: "Clear, timely behavioral coaching protects the guest and gives the employee a usable path forward.",
    standard: "Coach facts rather than identity; diagnose clarity, skill, system, environment, and willingness before choosing the response.",
    great: ["Correction is timely and specific", "Impact is connected to guest/team/safety", "One reset behavior is named", "Second-take evidence is captured"],
    language: ["Here is what I observed...", "Our standard is...", "Why that matters is...", "What I need from you now is...", "We are aligned?"],
    drill: "Convert five vague labels into observable coaching statements, then deliver a 60-second coach and require a second take.",
    floor: "Use one timely 60-second coach and one Keep / Start / Stop debrief during a real shift.",
    watch: ["Always and never", "Personality labels", "Public humiliation", "Saving everything for later", "Retraining a willingness problem"],
    certify: ["Behavioral observation", "Correct standard", "One clear reset", "Second-take improvement", "Appropriate privacy/urgency decision"],
    knowledgePrompt: "Which opening is behavioral coaching?",
    knowledgeOptions: ["You are lazy", "You do not care", "I watched three food runs sit while you were available", "Your attitude is the problem"],
    knowledgeAnswer: "I watched three food runs sit while you were available",
  },
  {
    week: 7,
    slug: "resourcefulness-80-20",
    title: "Week 7 - 80/20 Resourcefulness",
    summary: "Develop people who think, act, and bring recommendations upward.",
    minutes: 75,
    outcome: "Clarify facts, identify what is controllable, create options, take the next-best action, and recommend a move.",
    why: "Automatic escalation creates helplessness and leader bottlenecks. Resourcefulness separates the real constraint from the story around it.",
    standard: "Raise problems early with actions already taken, available options, and a recommendation; never hide safety or urgency.",
    great: ["Facts are separated from emotion", "Controllables are named", "Three options are considered", "A recommendation is brought upward"],
    language: ["What have you tried?", "What can you control?", "What is the next-best move?", "What are you recommending?"],
    drill: "Give a common roadblock with one fixed constraint; produce three controllable actions and a recommendation in 60 seconds.",
    floor: "When a problem is escalated, coach the thinking before supplying the answer unless guest safety or urgency requires direction.",
    watch: ["Hiding problems", "Reckless improvisation", "Learned helplessness", "Leaders answering too quickly", "Withholding support"],
    certify: ["One employee coached through the full 80/20 worksheet", "Sound recommendation", "Appropriate action and escalation"],
    knowledgePrompt: "What should an employee bring upward with a non-urgent problem?",
    knowledgeOptions: ["Only the complaint", "Facts, actions tried, options, and a recommendation", "A list of who caused it", "Nothing until it becomes urgent"],
    knowledgeAnswer: "Facts, actions tried, options, and a recommendation",
  },
  {
    week: 8,
    slug: "systems-predictability",
    title: "Week 8 - Systems + Predictability",
    summary: "Convert repeated problems into owned, visible, testable systems.",
    minutes: 90,
    outcome: "Define the standard, owner, trigger, method, verification, and recovery for every critical system.",
    why: "If the same capable people fail the same process, another reminder is not a solution. Mature operations learn from repetition.",
    standard: "Build processes that survive a manager's absence, make completion visible, and improve after breakdown.",
    great: ["One named owner", "A clear trigger", "Method and resources are defined", "Verification is visible", "Recovery path exists"],
    language: ["What system is allowing this result?", "Who owns it, what triggers it, and how do we verify completion?"],
    drill: "Build a six-part system for one recurring problem, hand it to another leader, and test it without extra explanation.",
    floor: "Capture one repeated failure, diagnose person versus system, and test one improvement during the week.",
    watch: ["Everyone owns it", "No trigger", "Hidden completion", "Missing resources", "Constant exceptions", "Systems living only in a manager's head"],
    certify: ["One real system built", "Named owner and verification", "Test completed", "Revision based on evidence"],
    knowledgePrompt: "Which element proves a system happened correctly?",
    knowledgeOptions: ["Intention", "Verification", "A reminder", "A strong manager"],
    knowledgeAnswer: "Verification",
  },
] as const satisfies readonly LeadershipWeekDefinition[];

export const LEADERSHIP_MODULES: readonly CurriculumModule[] = WEEK_DEFINITIONS.map((week) => ({
  id: `cur-leadership-week-${week.week}`,
  slug: week.slug,
  title: week.title,
  summary: week.summary,
  audience: LEADERSHIP_AUDIENCE,
  estimatedMinutes: week.minutes,
  outcomes: [week.outcome, "Teach the standard to another leader", "Produce live floor evidence"],
  ...(week.week > 0 ? { prerequisites: [`cur-leadership-week-${week.week - 1}`] } : {}),
  tags: ["leadership-os", `week-${week.week}`, "leadership-lab", "required"],
  sourceIds: ["leadership-os-1", "hospitality-reset-2026-08"],
  content: [
    { type: "principle", title: "Why it matters", body: week.why, tone: "navy" },
    { type: "standard", title: "The standard", body: week.standard, tone: "orange" },
    { type: "checklist", title: "What great looks like", items: week.great },
    { type: "script", title: "Leader language", lines: week.language },
    { type: "practice", title: "Run the drill", prompt: week.drill, successCriteria: week.certify },
    { type: "field-assignment", title: "On the floor", prompt: week.floor, successCriteria: week.certify },
    { type: "bullets", title: "Watch for", items: week.watch },
  ],
  assessment: {
    passingScore: 85,
    retryLimit: 1,
    practicalRequired: true,
    questions: [
      {
        id: `leadership-week-${week.week}-knowledge`,
        type: "multiple-choice",
        prompt: week.knowledgePrompt,
        options: week.knowledgeOptions,
        correctAnswer: week.knowledgeAnswer,
      },
      {
        id: `leadership-week-${week.week}-practical`,
        type: "practical",
        prompt: week.drill,
        rubric: week.certify,
      },
    ],
  },
}));

export const LEADERSHIP_PROGRAM = {
  id: "program-leadership-os",
  slug: "leadership-operating-system",
  title: "Hospitality Leadership Operating System",
  summary: "Build the culture. Train the standard. Lead the shift.",
  audience: LEADERSHIP_AUDIENCE,
  version: "2.0",
  effectiveDate: "2026-08-23",
  moduleIntervalDays: 7,
  moduleIds: LEADERSHIP_MODULES.map((module) => module.id),
  completionRule: "sequential",
  certification: {
    knowledgeScore: 85,
    practicalRequired: true,
    liveObservationRequired: true,
    auditDays: [30, 90],
  },
} as const satisfies CurriculumProgram;
