import { BARTENDER_AUDIENCE, SERVER_AUDIENCE, SUPPORT_AUDIENCE } from "./audiences";
import { COCKTAIL_MENU, FOOD_MENU_ITEMS } from "./menu";
import type { AssessmentQuestion, ContentBlock, CurriculumAudience, CurriculumModule, CurriculumProgram } from "./types";

type RoleModuleInput = {
  id: string;
  slug: string;
  title: string;
  summary: string;
  audience: CurriculumAudience;
  minutes: number;
  outcomes: readonly string[];
  prerequisites?: readonly string[];
  tags: readonly string[];
  sourceIds: readonly string[];
  content: readonly ContentBlock[];
  questions: readonly AssessmentQuestion[];
  passingScore?: number;
  criticalMisses?: readonly string[];
};

const roleModule = (input: RoleModuleInput): CurriculumModule => ({
  id: input.id,
  slug: input.slug,
  title: input.title,
  summary: input.summary,
  audience: input.audience,
  estimatedMinutes: input.minutes,
  outcomes: input.outcomes,
  ...(input.prerequisites ? { prerequisites: input.prerequisites } : {}),
  tags: input.tags,
  sourceIds: input.sourceIds,
  content: input.content,
  assessment: {
    passingScore: input.passingScore ?? 85,
    retryLimit: 2,
    practicalRequired: input.questions.some((question) => question.type === "practical"),
    ...(input.criticalMisses ? { criticalMisses: input.criticalMisses } : {}),
    questions: input.questions,
  },
});

const RESET_SOURCE = "hospitality-reset-2026-08";
const TRAINER_SOURCE = "trainer-os-1";
const FOOD_SOURCE = "food-menu-supplied";
const BAR_SOURCE = "bar-manual-2026-08";
const COCKTAIL_SOURCE = "cocktail-menu-supplied";

export const SERVER_ONBOARDING_MODULES = [
  roleModule({
    id: "cur-server-identity-readiness",
    slug: "server-identity-readiness",
    title: "Server Identity + Shift Readiness",
    summary: "Own the table's full experience from welcome through farewell while protecting the whole room.",
    audience: SERVER_AUDIENCE,
    minutes: 25,
    outcomes: ["Explain the server mission", "Arrive guest-ready", "Use CARE and five-foot ownership"],
    tags: ["server", "onboarding", "required"],
    sourceIds: [RESET_SOURCE, TRAINER_SOURCE],
    content: [
      { type: "principle", title: "Role mission", body: "Read the guest, guide decisions, pace the meal, communicate clearly, remove friction, and finish strong.", tone: "navy" },
      { type: "checklist", title: "Ready to work", items: ["On time and in uniform", "Coffee, food, and personal tasks handled", "Phone away", "Current 7shifts updates read", "Menu, specials, 86s, and station reviewed", "Tools and sidework ready"] },
      { type: "practice", title: "Five-foot scan", prompt: "Scan a staged section and choose the next three useful actions.", successCriteria: ["Guest priority first", "Food and safety protected", "Named handoff when needed", "No low-priority busywork"] },
    ],
    questions: [
      { id: "server-identity-1", type: "multiple-choice", prompt: "What is the server's highest responsibility?", options: ["Take orders quickly", "Own the guest's experience and handoffs", "Stay only in the assigned section", "Sell the highest-priced item"], correctAnswer: "Own the guest's experience and handoffs" },
      { id: "server-identity-practical", type: "practical", prompt: "Complete a readiness check and five-foot scan.", rubric: ["Prepared", "Prioritizes correctly", "Uses CARE", "Communicates ownership"] },
    ],
  }),
  roleModule({
    id: "cur-server-guest-journey",
    slug: "server-guest-journey",
    title: "The Ditch Guest Journey",
    summary: "Make every handoff from acknowledgment to goodbye observable, paced, and personal.",
    audience: SERVER_AUDIENCE,
    minutes: 35,
    outcomes: ["Execute the full service sequence", "Use specific check-backs", "Close every handoff"],
    prerequisites: ["cur-server-identity-readiness"],
    tags: ["server", "guest-journey", "required"],
    sourceIds: [RESET_SOURCE],
    content: [
      { type: "steps", title: "Service sequence", items: ["Acknowledge immediately; full greet as soon as guest care allows", "Discover first visit, occasion, appetite, pace, and guidance preference", "Guide beverage and food decisions", "Enter accurately and communicate timing/modifiers", "Course and pace with support handoffs", "Check back specifically while a correction is possible", "Clear and offer the next relevant moment", "Process payment promptly", "Thank and give a real reason to return"] },
      { type: "comparison", title: "Specific check-backs", leftLabel: "Avoid", rightLabel: "Use", rows: [
        { left: "Everything good?", right: "How is the spice level on the Jerk Shrimp Tacos?" },
        { left: "All set?", right: "Is the replacement temperature where it should be now?" },
      ] },
      { type: "practice", title: "Three table styles", prompt: "Run the sequence for a quiet pair, a first-time family, and a time-limited group.", successCriteria: ["Baseline consistent", "Pace adapts", "No scripted monologue", "Handoffs confirmed", "Strong close"] },
    ],
    questions: [
      { id: "server-journey-1", type: "multiple-choice", prompt: "When should a delay be communicated?", options: ["After the guest asks twice", "As soon as the server knows enough to give an honest update", "Only when the manager arrives", "At payment"], correctAnswer: "As soon as the server knows enough to give an honest update" },
      { id: "server-journey-practical", type: "practical", prompt: "Run one complete table role-play from arrival through farewell.", rubric: ["Acknowledgment", "Discovery", "Guidance", "Accuracy", "Pace", "Specific check-back", "Payment and close"] },
    ],
  }),
  roleModule({
    id: "cur-server-food-menu",
    slug: "server-food-menu",
    title: "Current Food Menu Fluency",
    summary: "Learn the current printed menu by category, fit, flavor, portion expectation, and approved source - never by stale script.",
    audience: SERVER_AUDIENCE,
    minutes: 60,
    outcomes: ["Locate and describe every current printed food item", "Set honest size and portion expectations", "Verify rather than infer allergy answers"],
    prerequisites: ["cur-server-guest-journey"],
    tags: ["server", "menu", "food", "required"],
    sourceIds: [FOOD_SOURCE, "allergy-source-current"],
    content: [
      { type: "menu-reference", title: "Current dining menu", itemIds: FOOD_MENU_ITEMS.map((item) => item.id), instruction: "Learn guest-facing name, category, description, printed price, and approved add-ons. Live POS controls current price and availability." },
      { type: "source-control", title: "Allergy boundary", sourceIds: ["allergy-source-current"], status: "verification-required", body: "Descriptions are not allergy certification. Never infer safety from an ingredient list, gluten-free label, cooking method, or past answer. Use the current allergy communication chain." },
      { type: "practice", title: "Menu map", prompt: "Sort surprise items into category, give a truthful 15-second description, name who it might fit, and state where to verify modifications.", successCriteria: ["Current item", "Correct category", "No invented ingredient", "Useful sensory fit", "No allergy assertion"] },
    ],
    questions: [
      { id: "server-food-1", type: "multiple-choice", prompt: "Where is the Quesadilla listed on the supplied current dining menu?", options: ["Tacos", "Bowls", "Platos", "Dessert"], correctAnswer: "Platos" },
      { id: "server-food-practical", type: "practical", prompt: "Describe five random current menu items and handle one allergy question.", rubric: ["Names and categories accurate", "Current price/source noted", "No invented facts", "Uses allergy chain"], critical: true },
    ],
    passingScore: 90,
    criticalMisses: ["Invents an allergy or ingredient answer"],
  }),
  roleModule({
    id: "cur-server-beverage-menu",
    slug: "server-beverage-menu",
    title: "Cocktails, Zero Proof, Wine + Rotating Beer",
    summary: "Guide beverage decisions using current flavor lanes while respecting recipe locks and rotating selections.",
    audience: SERVER_AUDIENCE,
    minutes: 45,
    outcomes: ["Describe current guest-facing cocktails", "Recognize verification-required recipes", "Verify beer in the current POS"],
    prerequisites: ["cur-server-food-menu"],
    tags: ["server", "menu", "beverage", "required"],
    sourceIds: [COCKTAIL_SOURCE, BAR_SOURCE, "beer-source-current"],
    content: [
      { type: "menu-reference", title: "Current cocktail and zero-proof menu", itemIds: COCKTAIL_MENU.map((item) => item.id), instruction: "Servers learn guest-facing ingredients and flavor lanes. Only bartenders train measured builds, and verification-required recipes remain locked until manager approval." },
      { type: "source-control", title: "Rotating beer", sourceIds: ["beer-source-current"], status: "rotating", body: "Selections change. Demonstrate the live verification path in the location's POS or current manager-posted list." },
      { type: "practice", title: "Beverage lanes", prompt: "Guide bright/classic, smoky/spicy, herbal/tropical, and zero-proof guest profiles using current items.", successCriteria: ["Asks before choosing", "Uses current flavor lane", "Does not teach locked recipe", "Offers zero proof with equal hospitality"] },
    ],
    questions: [
      { id: "server-bev-1", type: "multiple-choice", prompt: "Which current drink is the classic, bright starting point?", options: ["Hang 10", "Smoke on the Bay", "Mo Pain Yo", "Oaxaca Mule"], correctAnswer: "Hang 10" },
      { id: "server-bev-practical", type: "practical", prompt: "Guide four beverage profiles and show where the current beer list is verified.", rubric: ["Current items", "Flavor fit", "Source status respected", "Beer verified live"] },
    ],
  }),
  roleModule({
    id: "cur-server-passion-selling",
    slug: "server-passion-selling",
    title: "Server Passion Selling",
    summary: "Use Observe > Ask > Interpret > Recommend > Describe at the table without pressure.",
    audience: SERVER_AUDIENCE,
    minutes: 40,
    outcomes: ["Ask an efficient preference question", "Take a point of view", "Offer current pairings for a reason"],
    prerequisites: ["cur-server-food-menu", "cur-server-beverage-menu"],
    tags: ["server", "passion-selling", "required"],
    sourceIds: [RESET_SOURCE, FOOD_SOURCE, BAR_SOURCE],
    content: [
      { type: "steps", title: "The formula", items: ["Observe the guest's cues", "Ask one useful question", "Interpret the preference", "Recommend one direction", "Describe why it fits"] },
      { type: "menu-reference", title: "Verified practice pairings", itemIds: ["food-yuca-poppers", "drink-hang-10", "food-taco-carne-asada", "drink-smoke-on-the-bay", "food-taco-jerk-shrimp", "drink-pineapple-basil-smash", "food-wings", "drink-oaxaca-mule"], instruction: "Use pairings as conversation starters only when they fit the guest. State the flavor reason; do not push." },
      { type: "practice", title: "One size fits one", prompt: "Guide a first-time sharer, a light-appetite guest, a spice-seeker, and a zero-proof guest.", successCriteria: ["Question shapes recommendation", "Current facts", "Right-sized", "Truthful contrast", "Natural language"] },
    ],
    questions: [
      { id: "server-sell-1", type: "multiple-choice", prompt: "What is the best response to 'What's good?'", options: ["Everything", "The most expensive thing", "Ask one preference question, then take a position", "Read every special"], correctAnswer: "Ask one preference question, then take a position" },
      { id: "server-sell-practical", type: "practical", prompt: "Complete four 20-second recommendation role-plays.", rubric: ["Observe", "Ask", "Interpret", "Recommend", "Describe", "Current source"] },
    ],
  }),
  roleModule({
    id: "cur-server-pos-pacing-safety",
    slug: "server-pos-pacing-safety",
    title: "POS Accuracy, Pacing + Allergy Communication",
    summary: "Translate the guest's order into an accurate, timed, safely communicated handoff.",
    audience: SERVER_AUDIENCE,
    minutes: 55,
    outcomes: ["Enter current modifiers accurately", "Use seat/course/timing communication", "Execute the complete allergy escalation chain"],
    prerequisites: ["cur-server-passion-selling"],
    tags: ["server", "pos", "allergy", "safety", "required"],
    sourceIds: [RESET_SOURCE, "allergy-source-current"],
    content: [
      { type: "checklist", title: "Accuracy loop", items: ["Clarify the request", "Repeat material modifications", "Use the current POS button/modifier", "Set course and seat information", "Verbally communicate critical information", "Watch ticket flow", "Confirm delivery and check back"] },
      { type: "steps", title: "Allergy chain", items: ["Acknowledge without promising", "Mark the current POS procedure", "Communicate verbally", "Involve the manager", "Kitchen verifies what can be prepared safely", "Confirm protected delivery/handoff"] },
      { type: "scenario", title: "Complex order", prompt: "Enter and hand off a three-course order with a modification, an allergy concern, and a guest deadline.", successCriteria: ["No missed modifier", "Allergy chain complete", "Pacing realistic", "Kitchen/support handoffs named", "Guest updated"] },
    ],
    questions: [
      { id: "server-pos-1", type: "multiple-choice", prompt: "What must happen in addition to marking an allergy in the POS?", options: ["Nothing", "Verbal communication, manager involvement, and kitchen verification", "Tell the guest it is probably safe", "Ask another server"], correctAnswer: "Verbal communication, manager involvement, and kitchen verification", critical: true },
      { id: "server-pos-practical", type: "practical", prompt: "Complete the complex-order simulation.", rubric: ["Accurate entry", "Critical verbal handoff", "Pacing", "Guest communication", "Delivery confirmation"], critical: true },
    ],
    passingScore: 100,
    criticalMisses: ["Misses or guesses an allergy step", "Fails to communicate a material modifier"],
  }),
  roleModule({
    id: "cur-server-recovery-payment",
    slug: "server-recovery-payment",
    title: "Recovery, Payment + Strong Finish",
    summary: "Use L.A.S.T., protect role boundaries, close checks accurately, and end with genuine appreciation.",
    audience: SERVER_AUDIENCE,
    minutes: 40,
    outcomes: ["Run a same-team recovery", "Involve the MOD at the right moment", "Complete payment and farewell without friction"],
    prerequisites: ["cur-server-pos-pacing-safety"],
    tags: ["server", "recovery", "payment", "required"],
    sourceIds: [RESET_SOURCE, "leadership-os-1"],
    content: [
      { type: "steps", title: "L.A.S.T.", items: ["Listen fully", "Apologize for the experience", "Solve within role and manager boundaries", "Think about prevention after care is restored"] },
      { type: "checklist", title: "Finish strong", items: ["Check accuracy before presenting", "Process payment promptly", "Follow current cash/card procedure", "Return receipt/change cleanly", "Reference the guest's experience", "Thank sincerely", "Acknowledge departure"] },
      { type: "practice", title: "Two recoveries + close", prompt: "Recover a delayed item and a guest dislike, then close the check and farewell.", successCriteria: ["No blame", "Solution is honest", "MOD involved when required", "Specific follow-up", "Accurate payment", "Warm close"] },
    ],
    questions: [
      { id: "server-recovery-1", type: "multiple-choice", prompt: "What comes after a recovery solution?", options: ["Avoid the table", "Specific follow-up", "Only remove the item", "Explain who caused it"], correctAnswer: "Specific follow-up" },
      { id: "server-recovery-practical", type: "practical", prompt: "Complete the recovery and payment role-play.", rubric: ["Listen", "Acknowledge", "Own", "Follow up", "Accurate payment", "Strong farewell"] },
    ],
  }),
  roleModule({
    id: "cur-server-final-practical",
    slug: "server-final-practical",
    title: "Server Final Practical",
    summary: "Prove independent table ownership in a realistic sequence and survive a 7/30-day audit.",
    audience: SERVER_AUDIENCE,
    minutes: 75,
    outcomes: ["Prepare a section", "Own a full realistic table", "Demonstrate source safety and recovery"],
    prerequisites: ["cur-server-recovery-payment"],
    tags: ["server", "certification", "final-practical", "required"],
    sourceIds: [RESET_SOURCE, TRAINER_SOURCE, FOOD_SOURCE, BAR_SOURCE],
    content: [
      { type: "field-assignment", title: "Final practicum", prompt: "Prepare a section; greet and discover; guide a current menu decision; enter and course an order; communicate an allergy; handle a recovery; complete payment, sidework, and handoff.", successCriteria: ["Knowledge proof", "Independent performance", "No critical miss", "Trainer does not carry result", "7- and 30-day audit scheduled"] },
    ],
    questions: [
      { id: "server-final-knowledge", type: "short-answer", prompt: "Teach back the guest journey, CARE, Passion Selling, allergy chain, and L.A.S.T.", rubric: ["Accurate", "Observable", "Current-source discipline"] },
      { id: "server-final-live", type: "practical", prompt: "Complete the server final practicum.", rubric: ["Readiness", "Guest journey", "Menu guidance", "POS/pacing", "Safety", "Recovery", "Payment/handoff"], critical: true },
    ],
    passingScore: 90,
    criticalMisses: ["Allergy or safety miss", "Invented menu fact", "Dishonest sign-off", "Guest abandonment"],
  }),
] as const satisfies readonly CurriculumModule[];

export const BARTENDER_ONBOARDING_MODULES = [
  roleModule({
    id: "cur-bartender-identity-journey",
    slug: "bartender-identity-guest-journey",
    title: "Bar Identity + Guest Journey",
    summary: "Be host, craftsperson, traffic controller, and good-vibe mechanic with warm people and exact execution.",
    audience: BARTENDER_AUDIENCE,
    minutes: 30,
    outcomes: ["Acknowledge new guests within 30 seconds", "Run discover-to-close sequence", "Own the ticket, pace, cleanup, and handoff"],
    tags: ["bartender", "onboarding", "required"],
    sourceIds: [BAR_SOURCE, RESET_SOURCE],
    content: [
      { type: "principle", title: "The bar standard", body: "Hospitality without standards is chaos. Standards without hospitality is a vending machine. Ditch needs warm people and exact execution.", tone: "navy" },
      { type: "steps", title: "Bar guest journey", items: ["0-30 seconds: acknowledge", "Discover one useful preference", "Recommend one confident choice and reason", "Build and deliver to spec", "Two-sip check", "Continue, pace water/food/alcohol, close accurately, and say goodbye"] },
      { type: "practice", title: "Buried-but-visible", prompt: "Acknowledge three arrivals while managing a ticket rail without making a promise you cannot keep.", successCriteria: ["Every guest seen", "Next step stated", "Tickets stay accurate", "Tone remains calm"] },
    ],
    questions: [
      { id: "bartender-identity-1", type: "multiple-choice", prompt: "What is the acknowledgment target at the bar?", options: ["30 seconds", "90 seconds", "When the ticket rail is empty", "After the guest waves"], correctAnswer: "30 seconds" },
      { id: "bartender-identity-practical", type: "practical", prompt: "Run the buried-but-visible scenario.", rubric: ["Fast acknowledgment", "Accurate next step", "Ticket control", "Warm close"] },
    ],
  }),
  roleModule({
    id: "cur-bartender-safe-responsible",
    slug: "bartender-safe-responsible-service",
    title: "Safe + Responsible Service",
    summary: "Protect ID, intoxication, allergy, glass/ice, and incident boundaries without improvisation.",
    audience: BARTENDER_AUDIENCE,
    minutes: 50,
    outcomes: ["Own the ID decision", "Use current responsible-service escalation", "Execute the allergy and broken-glass stop points"],
    prerequisites: ["cur-bartender-identity-journey"],
    tags: ["bartender", "safety", "alcohol", "allergy", "required"],
    sourceIds: [BAR_SOURCE, "allergy-source-current"],
    content: [
      { type: "standard", title: "Never transfer the ID responsibility", body: "The employee serving alcohol remains responsible for checking identification even when security is present. Use current law and company policy; involve the MOD before risk grows.", tone: "warning" },
      { type: "checklist", title: "Critical stop points", items: ["Uncertain or invalid ID", "Signs of intoxication or rapid consumption", "Allergy uncertainty", "Broken glass in or near ice", "Unsafe spill or equipment condition", "Conflict or security concern"] },
      { type: "scenario", title: "Responsible-service triad", prompt: "Handle a questionable ID, a guest showing impairment, and an allergy question without guessing or escalating emotion.", successCriteria: ["Follows current policy", "MOD involved promptly", "Same-team language", "Incident/handoff documented as required"] },
    ],
    questions: [
      { id: "bartender-safe-1", type: "true-false", prompt: "Security checking an ID removes the bartender's responsibility.", correctAnswer: false, critical: true },
      { id: "bartender-safe-practical", type: "practical", prompt: "Complete the responsible-service triad.", rubric: ["ID ownership", "Pacing/refusal boundary", "Allergy chain", "MOD handoff", "Professional language"], critical: true },
    ],
    passingScore: 100,
    criticalMisses: ["Serves without required ID check", "Guesses an allergy answer", "Fails to stop for broken glass/ice risk"],
  }),
  roleModule({
    id: "cur-bartender-station-technique",
    slug: "bartender-station-technique",
    title: "Station Readiness + Build Technique",
    summary: "Set the station once, jigger every pour, use fresh ice, and make repeatability visible.",
    audience: BARTENDER_AUDIENCE,
    minutes: 60,
    outcomes: ["Verify the approved well and back-bar layout", "Choose the correct method", "Build cleanly with controlled dilution and finish"],
    prerequisites: ["cur-bartender-safe-responsible"],
    tags: ["bartender", "technique", "station", "required"],
    sourceIds: [BAR_SOURCE],
    content: [
      { type: "checklist", title: "Station standard", items: ["Both wells mirror approved setup", "Bottles returned to labeled locations", "Tools clean and at home", "Fresh hard ice", "Correct glassware and garnish", "Backups, labels, and dates verified", "Dry floor and clear paths"] },
      { type: "steps", title: "Build discipline", items: ["Read the complete ticket and modifiers", "Add lower-cost modifiers first and base spirit after", "Add ice last", "Jigger every pour", "Shake/stir with clean hard ice", "Serve over fresh ice unless recipe explicitly says dump/pour", "Add carbonation after shaking/stirring", "Wipe the vessel and present the clean rim"] },
      { type: "practice", title: "Technique stations", prompt: "Demonstrate build, shake, stir, double strain, top, frozen-service check, draft pour, and wine-pour verification.", successCriteria: ["Method matches source", "No reused shaker ice", "Carbonation handled last", "Wine pour uses current verified measure", "Station resets between reps"] },
    ],
    questions: [
      { id: "bartender-technique-1", type: "multiple-choice", prompt: "When is carbonation normally added?", options: ["Before shaking", "After shaking or stirring", "With the base spirit", "It does not matter"], correctAnswer: "After shaking or stirring" },
      { id: "bartender-technique-practical", type: "practical", prompt: "Complete the technique stations and full reset.", rubric: ["Measurement", "Method", "Temperature/dilution", "Presentation", "Reset"] },
    ],
  }),
  roleModule({
    id: "cur-bartender-approved-signatures-1",
    slug: "approved-signatures-margaritas",
    title: "Approved Signatures I: Margarita Lane",
    summary: "Build the approved current margaritas exactly: glass, ice, method, ounces, rim, and garnish.",
    audience: BARTENDER_AUDIENCE,
    minutes: 80,
    outcomes: ["Build Hang 10, Smoke on the Bay, Holla Pain Yo!, and Mo Pain Yo! from memory", "Explain the flavor contrast", "Warn accurately about the hotter spicy option"],
    prerequisites: ["cur-bartender-station-technique"],
    tags: ["bartender", "recipes", "margaritas", "required"],
    sourceIds: [BAR_SOURCE, COCKTAIL_SOURCE],
    content: [
      { type: "menu-reference", title: "Approved recipe set", itemIds: ["drink-hang-10", "drink-smoke-on-the-bay", "drink-holla-pain-yo", "drink-mo-pain-yo"], instruction: "Use every measured build, method, rim, garnish, and glass exactly as listed in the controlled curriculum." },
      { type: "comparison", title: "Spice guidance", leftLabel: "Holla Pain Yo!", rightLabel: "Mo Pain Yo!", rows: [{ left: "Jalapeño, tart, lively", right: "Jalapeño plus habanero; explicitly the hotter option" }] },
      { type: "practice", title: "Four-drink practical", prompt: "Build all four in random order from memory, then identify one planted finish or measurement miss.", successCriteria: ["Exact ounces", "Correct method and fresh ice", "Correct rim/garnish", "Clean presentation", "Station reset"] },
    ],
    questions: [
      { id: "bartender-marg-1", type: "multiple-choice", prompt: "Which verified spicy marg uses both jalapeño and habanero?", options: ["Hang 10", "Smoke on the Bay", "Holla Pain Yo!", "Mo Pain Yo!"], correctAnswer: "Mo Pain Yo!" },
      { id: "bartender-marg-practical", type: "practical", prompt: "Pass the random four-drink build practical.", rubric: ["Recipe", "Glass/ice/method", "Finish", "Flavor explanation", "Zero source guessing"], critical: true },
    ],
    passingScore: 90,
    criticalMisses: ["Free-pours or invents a recipe", "Misses a material modifier"],
  }),
  roleModule({
    id: "cur-bartender-approved-signatures-2",
    slug: "approved-signatures-house-zero-proof",
    title: "Approved Signatures II: House + Zero Proof",
    summary: "Build the currently approved herbal, refreshing, rum, and zero-proof signatures with equal care.",
    audience: BARTENDER_AUDIENCE,
    minutes: 95,
    outcomes: ["Build six approved signatures", "Handle herbs and carbonation correctly", "Give zero-proof guests the full hospitality experience"],
    prerequisites: ["cur-bartender-approved-signatures-1"],
    tags: ["bartender", "recipes", "zero-proof", "required"],
    sourceIds: [BAR_SOURCE, COCKTAIL_SOURCE],
    content: [
      { type: "menu-reference", title: "Approved recipe set", itemIds: ["drink-pineapple-basil-smash", "drink-oaxaca-mule", "drink-cool-as-a-cucumber", "drink-mojito", "drink-watermelon-cooler", "drink-no-jito", "drink-pina-no-lada"], instruction: "Train only these approved builds in this module. Use fresh herbs, correct carbonation order, exact finish, and a clean reset." },
      { type: "practice", title: "Random build + guest guidance", prompt: "Build four random items, including one zero-proof, and guide a guest through the flavor difference.", successCriteria: ["Exact source", "Herbs handled cleanly", "Carbonation last", "Zero proof receives equal presentation", "Guest language is current and human"] },
    ],
    questions: [
      { id: "bartender-house-1", type: "multiple-choice", prompt: "Which approved cocktail is topped with ginger beer after double straining?", options: ["Oaxaca Mule", "Mojito", "Hang 10", "Cool as a Cucumber"], correctAnswer: "Oaxaca Mule" },
      { id: "bartender-house-practical", type: "practical", prompt: "Complete the random build and guidance practical.", rubric: ["Recipe", "Technique", "Finish", "Zero-proof equality", "Guest guidance"] },
    ],
  }),
  roleModule({
    id: "cur-bartender-locked-rotating",
    slug: "verification-required-rotating-content",
    title: "Recipe Locks + Rotating Products",
    summary: "Recognize when the safe, professional answer is to stop, verify, and update the source.",
    audience: BARTENDER_AUDIENCE,
    minutes: 35,
    outcomes: ["Identify every verification-required recipe", "Avoid the Ancho quantity typo", "Verify beer, wine pour, pars, and recipe locks"],
    prerequisites: ["cur-bartender-approved-signatures-2"],
    tags: ["bartender", "source-control", "verification-required", "required"],
    sourceIds: [BAR_SOURCE, "beer-source-current", "allergy-source-current"],
    content: [
      { type: "source-control", title: "Do not train until locked", sourceIds: [BAR_SOURCE], status: "verification-required", body: "Ancho Average Marg, Sunburnt Summer, Frozen Paloma, Da Painkiller, Island Rum Punch, and Hibiscus Refresher require manager approval on the recipe lock. The Ancho printed Tanteo quantity is an apparent source error and must not be taught. Pink salt, measured wine pour, and current pars also require verification where the source flags conflict." },
      { type: "source-control", title: "Rotating beer", sourceIds: ["beer-source-current"], status: "rotating", body: "Current POS and the manager-posted list win. Demonstrate the verification path; do not certify a historic six-beer list." },
      { type: "scenario", title: "Source conflict", prompt: "A teammate quotes an old recipe, the printed manual conflicts, and a guest is waiting. Protect the guest while resolving the source.", successCriteria: ["Stops the guess", "Uses manager/current lock", "Sets honest guest expectation", "Updates/escalates source mismatch", "Does not create a local workaround"] },
    ],
    questions: [
      { id: "bartender-lock-1", type: "multi-select", prompt: "Which items remain verification-required?", options: ["Ancho Average", "Sunburnt Summer", "Frozen Paloma", "Da Painkiller", "Island Rum Punch", "Hibiscus Refresher", "Hang 10"], correctAnswer: ["Ancho Average", "Sunburnt Summer", "Frozen Paloma", "Da Painkiller", "Island Rum Punch", "Hibiscus Refresher"], critical: true },
      { id: "bartender-lock-practical", type: "practical", prompt: "Resolve the source-conflict scenario and show the current beer verification path.", rubric: ["No guessed build", "Correct authority", "Guest protected", "Source mismatch logged", "Beer verified live"], critical: true },
    ],
    passingScore: 100,
    criticalMisses: ["Teaches the Ancho typo", "Builds a locked recipe from memory", "States rotating beer as fixed"],
  }),
  roleModule({
    id: "cur-bartender-passion-pairing",
    slug: "bartender-passion-selling-pairing",
    title: "Bar Passion Selling + Pairing",
    summary: "Discover the guest's flavor lane and recommend with a current, truthful reason.",
    audience: BARTENDER_AUDIENCE,
    minutes: 40,
    outcomes: ["Use one useful beverage question", "Recommend across spirited and zero-proof lanes", "Pair only current approved items"],
    prerequisites: ["cur-bartender-locked-rotating"],
    tags: ["bartender", "passion-selling", "pairing", "required"],
    sourceIds: [BAR_SOURCE, FOOD_SOURCE, RESET_SOURCE],
    content: [
      { type: "steps", title: "Discover the lane", items: ["Bright and refreshing", "Smoky and spicy", "Herbal and tropical", "Spirit-forward", "Beer or wine", "Zero proof"] },
      { type: "menu-reference", title: "Approved pairing lab", itemIds: ["drink-hang-10", "food-yuca-poppers", "food-taco-baja-fish", "drink-smoke-on-the-bay", "food-taco-carne-asada", "food-taco-pork-belly", "drink-pineapple-basil-smash", "food-taco-jerk-shrimp", "food-tuna-tartare", "drink-oaxaca-mule", "food-taco-pork-carnitas", "food-wings"], instruction: "Explain the flavor reason. Availability, allergy safety, and preference still require current verification." },
      { type: "practice", title: "Four guest profiles", prompt: "Guide a vodka-soda regular, spice-seeker, food-pairing guest, and zero-proof guest.", successCriteria: ["Asks before recommending", "Takes a position", "Current verified item", "Pairing reason", "No pressure"] },
    ],
    questions: [
      { id: "bartender-pair-1", type: "multiple-choice", prompt: "What pairing reason is listed for Hang 10 with fried or rich food?", options: ["Smoke mirrors char", "Lime and salt wake up the food", "Coconut adds richness", "Ginger adds heat"], correctAnswer: "Lime and salt wake up the food" },
      { id: "bartender-pair-practical", type: "practical", prompt: "Complete four beverage-guidance role-plays.", rubric: ["Discovery", "Verified recommendation", "Truthful description", "Pairing fit", "Zero-proof inclusion"] },
    ],
  }),
  roleModule({
    id: "cur-bartender-ticket-recovery",
    slug: "bartender-ticket-flow-recovery",
    title: "Ticket Flow, Volume + Recovery",
    summary: "Stay fast by staying organized; communicate before guests chase and recover without blame.",
    audience: BARTENDER_AUDIENCE,
    minutes: 55,
    outcomes: ["Prioritize a realistic rail", "Use 10 for 10 without stopping the bar", "Complete L.A.S.T. and same-team handoffs"],
    prerequisites: ["cur-bartender-passion-pairing"],
    tags: ["bartender", "volume", "recovery", "required"],
    sourceIds: [BAR_SOURCE, RESET_SOURCE, "leadership-os-1"],
    content: [
      { type: "checklist", title: "Volume control", items: ["Read full tickets and modifiers", "Batch safe movements, never guesses", "Communicate aging tickets", "Reset tools and bottles in motion", "Use named handoffs", "Protect water, food, responsible service, and guest acknowledgment"] },
      { type: "steps", title: "Recovery", items: ["Listen", "Apologize without excuse", "Solve within authority or hand to MOD", "Return for a two-sip/specific check", "Think about source, prep, ticket, or system cause"] },
      { type: "practice", title: "Rail simulation", prompt: "Manage a realistic mixed rail with one modifier, one delayed drink, one guest dislike, and one 10 for 10 reset.", successCriteria: ["Priority and accuracy", "Guests remain visible", "No reused ice or shortcuts", "Recovery complete", "Station returns to standard"] },
    ],
    questions: [
      { id: "bartender-flow-1", type: "multiple-choice", prompt: "What protects speed most reliably?", options: ["Free-pouring", "Skipping reset", "Organized station and exact repeatable method", "Ignoring guests until rail is clear"], correctAnswer: "Organized station and exact repeatable method" },
      { id: "bartender-flow-practical", type: "practical", prompt: "Pass the rail simulation.", rubric: ["Ticket accuracy", "Pace", "Communication", "Recovery", "Responsible service", "Reset"] },
    ],
  }),
  roleModule({
    id: "cur-bartender-open-close-control",
    slug: "bartender-open-close-control",
    title: "Open, Close, Clean + Control",
    summary: "Leave the next bartender a verified station, not a scavenger hunt or a mystery batch.",
    audience: BARTENDER_AUDIENCE,
    minutes: 55,
    outcomes: ["Complete opening and closing from current checklists", "Use labels, FIFO, waste, and maintenance controls", "Sign only work personally completed or verified"],
    prerequisites: ["cur-bartender-ticket-recovery"],
    tags: ["bartender", "opening", "closing", "control", "required"],
    sourceIds: [BAR_SOURCE, RESET_SOURCE],
    content: [
      { type: "checklist", title: "Complete reset", items: ["Wells, bottles, tools, mats", "Soda-gun nozzles and holsters", "Sinks and glass washer", "POS and cash handoff under current policy", "Coolers, glassware, garnish, labels, and dates", "Garbage, floors, visible clutter", "Shortages/86s/maintenance communicated"] },
      { type: "standard", title: "Signature meaning", body: "Initial only what you personally completed or physically verified. False or repeated incomplete sign-offs are performance and integrity issues.", tone: "warning" },
      { type: "practice", title: "Close-to-open audit", prompt: "Close a staged bar, then have another qualified person open it using only the approved checklist and recorded handoff.", successCriteria: ["No hidden unfinished task", "Counts and labels accurate", "Equipment clean", "Shortage and maintenance loops closed", "Second person can open without rescue"] },
    ],
    questions: [
      { id: "bartender-close-1", type: "true-false", prompt: "Initialing a checklist means you completed or physically verified the work.", correctAnswer: true, critical: true },
      { id: "bartender-close-practical", type: "practical", prompt: "Complete the close-to-open audit.", rubric: ["Readiness", "Sanitation", "Labels/FIFO", "Control", "Handoff", "Honest verification"], critical: true },
    ],
    passingScore: 100,
    criticalMisses: ["False sign-off", "Unsafe chemical/glass/ice condition", "Unreported control issue"],
  }),
  roleModule({
    id: "cur-bartender-final-practical",
    slug: "bartender-final-practical",
    title: "Bartender Final Practical",
    summary: "Prove hospitality, recipe accuracy, safety, volume control, and station ownership as one complete performance.",
    audience: BARTENDER_AUDIENCE,
    minutes: 120,
    outcomes: ["Open and verify a station", "Produce assigned approved drinks accurately", "Manage guest, safety, recovery, and close"],
    prerequisites: ["cur-bartender-open-close-control"],
    tags: ["bartender", "certification", "final-practical", "required"],
    sourceIds: [BAR_SOURCE, RESET_SOURCE, TRAINER_SOURCE],
    content: [
      { type: "field-assignment", title: "Final practicum", prompt: "Open and verify; complete a random approved recipe practical; manage a realistic ticket rail; guide three guest preferences including zero proof; respond to an allergy and responsible-service scenario; close and document the station.", successCriteria: ["Knowledge", "Independent performance", "Consistency", "No locked recipe taught", "No critical miss", "7- and 30-day audit"] },
    ],
    questions: [
      { id: "bartender-final-knowledge", type: "short-answer", prompt: "Teach back the bar guest journey, source hierarchy, approved vs. locked recipes, and critical stop points.", rubric: ["Accurate", "Current", "No recipe typo repeated", "Escalation boundaries"] },
      { id: "bartender-final-live", type: "practical", prompt: "Complete the bartender final practicum.", rubric: ["Station", "Recipes", "Rail", "Hospitality", "Responsible service", "Allergy", "Recovery", "Close/control"], critical: true },
    ],
    passingScore: 90,
    criticalMisses: ["Alcohol, allergy, or safety miss", "Free-pour or invented recipe", "Teaches locked content", "Dishonest control record"],
  }),
] as const satisfies readonly CurriculumModule[];

export const SUPPORT_ONBOARDING_MODULES = [
  roleModule({
    id: "cur-support-shared-core",
    slug: "support-shared-core",
    title: "Support Identity + Shared Core",
    summary: "Make hospitality feel effortless by protecting welcome, accuracy, pace, cleanliness, readiness, and communication.",
    audience: SUPPORT_AUDIENCE,
    minutes: 30,
    outcomes: ["Use CARE and five-foot ownership", "Move with urgency without panic", "Understand shared core and branch certification"],
    tags: ["support", "onboarding", "required"],
    sourceIds: [RESET_SOURCE, TRAINER_SOURCE],
    content: [
      { type: "principle", title: "Role mission", body: "Protect the guest experience underneath the visible service: welcome, accurate food, water, clean tables, safe movement, and closed communication loops.", tone: "navy" },
      { type: "standard", title: "Branch certification", body: "Every Support Staff teammate proves the shared core, then certifies separately for Host, Busser, Food Runner/Expo, or Barback duties. Cross-training adds proof; it does not transfer automatically.", tone: "orange" },
      { type: "practice", title: "Five-foot ownership", prompt: "Identify five support needs in a staged room and prioritize them.", successCriteria: ["Safety and food first", "Arrival and guest visibility", "Named handoffs", "No panic", "Own role remains covered"] },
    ],
    questions: [
      { id: "support-core-1", type: "true-false", prompt: "Certification in one support branch automatically certifies every branch.", correctAnswer: false },
      { id: "support-core-practical", type: "practical", prompt: "Complete the staged-room priority drill.", rubric: ["Sees cues", "Prioritizes", "Owns or transfers", "Closes loops"] },
    ],
  }),
  roleModule({
    id: "cur-support-safety-map",
    slug: "support-safety-map-communication",
    title: "Safety, Restaurant Map + Communication",
    summary: "Know the room, table numbers, traffic paths, tools, hazards, and exact language for a clean handoff.",
    audience: SUPPORT_AUDIENCE,
    minutes: 45,
    outcomes: ["Navigate table/station map", "Handle hot plates, glass, spills, lifting, and chemicals safely", "Use names, table numbers, and exact actions"],
    prerequisites: ["cur-support-shared-core"],
    tags: ["support", "safety", "communication", "required"],
    sourceIds: [RESET_SOURCE, "allergy-source-current"],
    content: [
      { type: "checklist", title: "Critical hazards", items: ["Hot plate and tray handling", "Broken glass and ice", "Wet floors and spills", "Chemical labels and separation", "Safe lifting and traffic flow", "Allergy callouts", "Guest-area hazards"] },
      { type: "script", title: "Closed-loop language", lines: ["Alex, hot food for 24 needs a runner now - can you own it?", "Heard - table 24, I have it.", "Confirmed delivered; table still needs one item and the server knows."] },
      { type: "practice", title: "Map and hazards", prompt: "Navigate surprise tables, carry/announce safely, correct two staged hazards, and complete a named handoff.", successCriteria: ["Correct destination", "Safe path", "Exact language", "Hazard not walked past", "Handoff verified"] },
    ],
    questions: [
      { id: "support-safety-1", type: "multiple-choice", prompt: "What should a support handoff include?", options: ["A general call to the room", "A name, exact action, confirmation, and follow-up", "A point toward the station", "Only the table number"], correctAnswer: "A name, exact action, confirmation, and follow-up" },
      { id: "support-safety-practical", type: "practical", prompt: "Complete the map, hazard, and handoff practical.", rubric: ["Map accuracy", "Safe movement", "Hazard response", "Closed loop"], critical: true },
    ],
    passingScore: 100,
    criticalMisses: ["Misses a safety or allergy callout", "Unsafe glass/ice handling"],
  }),
  roleModule({
    id: "cur-support-host-branch",
    slug: "support-host-branch",
    title: "Host Branch: Welcome + Flow",
    summary: "Make every arrival visible, quote waits honestly, seat with judgment, and transfer the table cleanly.",
    audience: SUPPORT_AUDIENCE,
    minutes: 55,
    outcomes: ["Acknowledge every arrival", "Use current reservation/wait procedure", "Complete host-to-server handoff"],
    prerequisites: ["cur-support-safety-map"],
    tags: ["support", "host", "branch-certification"],
    sourceIds: [RESET_SOURCE, TRAINER_SOURCE],
    content: [
      { type: "steps", title: "Host journey", items: ["Acknowledge immediately", "Learn name, party, needs, and context", "Use current reservation/wait system", "Quote honestly and update before being chased", "Seat with table/section/accessibility awareness", "Provide menus and a warm transfer", "Confirm the table is acknowledged"] },
      { type: "scenario", title: "Arrival stack", prompt: "Manage a reservation, walk-in, phone call, and accessibility request arriving together.", successCriteria: ["Everyone acknowledged", "Priority explained", "Wait quote honest", "Accessibility protected", "Server handoff closed"] },
    ],
    questions: [
      { id: "support-host-1", type: "multiple-choice", prompt: "A guest may wait during volume, but should never...", options: ["Ask a question", "Feel invisible", "Receive an update", "See the host help another guest"], correctAnswer: "Feel invisible" },
      { id: "support-host-practical", type: "practical", prompt: "Complete the arrival-stack practical.", rubric: ["Acknowledgment", "System accuracy", "Wait communication", "Seating judgment", "Handoff"] },
    ],
  }),
  roleModule({
    id: "cur-support-busser-branch",
    slug: "support-busser-branch",
    title: "Busser Branch: Maintain + Reset",
    summary: "Read clearing cues, maintain water and the tabletop, and return the whole zone to guest-ready standard.",
    audience: SUPPORT_AUDIENCE,
    minutes: 50,
    outcomes: ["Pre-bus without interrupting the moment", "Execute a complete reset", "Keep dish flow and surrounding zone safe"],
    prerequisites: ["cur-support-safety-map"],
    tags: ["support", "busser", "branch-certification"],
    sourceIds: [RESET_SOURCE, TRAINER_SOURCE],
    content: [
      { type: "checklist", title: "Complete reset", items: ["Read the clearing cue", "Remove debris safely", "Clean and dry full surface and seating", "Replace approved settings in mapped positions", "Check floor and surrounding zone", "Confirm the table is truly ready"] },
      { type: "practice", title: "Three resets", prompt: "Complete one routine reset, one volume reset, and one reset with a staged surrounding-zone miss.", successCriteria: ["No rushed safety miss", "Surface and seating complete", "Settings accurate", "Floor/zone checked", "Table released as ready"] },
    ],
    questions: [
      { id: "support-busser-1", type: "true-false", prompt: "A reset is complete once the tabletop is wiped.", correctAnswer: false },
      { id: "support-busser-practical", type: "practical", prompt: "Complete three resets to standard.", rubric: ["Clearing cues", "Sanitation", "Settings", "Surrounding zone", "Volume pace"] },
    ],
  }),
  roleModule({
    id: "cur-support-runner-branch",
    slug: "support-food-runner-expo-branch",
    title: "Food Runner + Expo Branch: Accuracy at the Pass",
    summary: "Protect item, table, seat, allergy callout, temperature, presentation, and missing-item recovery.",
    audience: SUPPORT_AUDIENCE,
    minutes: 65,
    outcomes: ["Read current tickets accurately", "Identify current menu items without guessing", "Announce, deliver, and recover missing items safely"],
    prerequisites: ["cur-support-safety-map"],
    tags: ["support", "runner", "expo", "branch-certification"],
    sourceIds: [FOOD_SOURCE, RESET_SOURCE, "allergy-source-current"],
    content: [
      { type: "menu-reference", title: "Food identification", itemIds: FOOD_MENU_ITEMS.map((item) => item.id), instruction: "Recognize current names and visible presentation from approved live training. Do not infer hidden ingredients or allergy safety from appearance." },
      { type: "steps", title: "Pass-to-table accuracy", items: ["Read full ticket and callouts", "Match item, table, seat, and modifier", "Stop for allergy verification", "Carry safely and protect temperature", "Announce the item clearly", "Confirm missing/extra items", "Return or hand off any issue by name"] },
      { type: "practice", title: "Runner rail", prompt: "Run a mixed rail with a modifier, allergy callout, missing side, and table-number variation.", successCriteria: ["Ticket accuracy", "Allergy stop point", "Safe carry", "Clear announcement", "Missing item owned through closure"] },
    ],
    questions: [
      { id: "support-runner-1", type: "multiple-choice", prompt: "What should happen when an allergy item reaches the pass without the required verification?", options: ["Run it quickly", "Pause and involve the required manager/kitchen verification", "Ask the guest", "Remove the garnish"], correctAnswer: "Pause and involve the required manager/kitchen verification", critical: true },
      { id: "support-runner-practical", type: "practical", prompt: "Pass the runner-rail practical.", rubric: ["Item/table/seat", "Modifiers", "Allergy", "Safe movement", "Announcement", "Recovery"], critical: true },
    ],
    passingScore: 100,
    criticalMisses: ["Runs unverified allergy item", "Wrong table/item without correction", "Unsafe hot/glass handling"],
  }),
  roleModule({
    id: "cur-support-volume-system",
    slug: "support-volume-system",
    title: "Volume System: Priorities, Zones + 10 for 10",
    summary: "Stay urgent and calm by assigning zones, naming priorities, and resetting drift before it compounds.",
    audience: SUPPORT_AUDIENCE,
    minutes: 40,
    outcomes: ["Choose the next highest-value action", "Help without creating duplication", "Use and receive a neutral reset"],
    prerequisites: ["cur-support-safety-map"],
    tags: ["support", "volume", "teamwork", "required"],
    sourceIds: [RESET_SOURCE, "leadership-os-1"],
    content: [
      { type: "steps", title: "Priority ladder", items: ["Immediate safety/allergy risk", "Hot food, kitchen bell, and ticket accuracy", "Invisible arrival or direct guest need", "Drink/water/table maintenance", "Reset and readiness", "Low-priority sidework"] },
      { type: "standard", title: "10 for 10", body: "When a zone drifts, anyone may call a roughly 30-second reset. Say Heard, join the reset, verify completion, recognize it, and return to service.", tone: "orange" },
      { type: "practice", title: "Volume matrix", prompt: "Prioritize ten simultaneous cues, make two named handoffs, and complete one 10 for 10.", successCriteria: ["Safety and hot food protected", "No guest invisible", "No duplicate ownership", "Reset is fast and complete"] },
    ],
    questions: [
      { id: "support-volume-1", type: "multiple-choice", prompt: "What beats low-priority sidework?", options: ["Reorganizing straws", "Food in the pass and a waiting guest", "Polishing an unused shelf", "A long teammate conversation"], correctAnswer: "Food in the pass and a waiting guest" },
      { id: "support-volume-practical", type: "practical", prompt: "Complete the volume-matrix drill.", rubric: ["Priorities", "Zone ownership", "Named handoffs", "10 for 10", "Calm tone"] },
    ],
  }),
  roleModule({
    id: "cur-support-guest-questions-recovery",
    slug: "support-guest-questions-recovery",
    title: "Guest Questions, Recovery + Strong Handoffs",
    summary: "Own the question without bluffing, pointing, or promising beyond the role.",
    audience: SUPPORT_AUDIENCE,
    minutes: 35,
    outcomes: ["Use 'let me confirm' accurately", "Complete warm transfers", "Start L.A.S.T. and involve the right owner"],
    prerequisites: ["cur-support-volume-system"],
    tags: ["support", "recovery", "handoff", "required"],
    sourceIds: [RESET_SOURCE, "allergy-source-current"],
    content: [
      { type: "comparison", title: "Own without inventing", leftLabel: "Avoid", rightLabel: "Use", rows: [
        { left: "I do not know.", right: "Let me confirm that so I give you the right answer." },
        { left: "Ask your server.", right: "I can help with that. Let me bring your server over and explain what you need." },
        { left: "The kitchen is backed up.", right: "Thank you for waiting. I am getting an exact update now." },
      ] },
      { type: "practice", title: "Boundary reps", prompt: "Handle a menu question, allergy question, delayed item, and guest dislike from the support role.", successCriteria: ["No guess", "Correct owner", "Warm transfer", "Guest sees action", "Follow-up closes loop"] },
    ],
    questions: [
      { id: "support-recovery-1", type: "multiple-choice", prompt: "What is the correct response when you do not know a menu answer?", options: ["Guess confidently", "Say it is probably fine", "Confirm from the approved source/right person and return", "Point at the menu"], correctAnswer: "Confirm from the approved source/right person and return" },
      { id: "support-recovery-practical", type: "practical", prompt: "Complete four boundary reps.", rubric: ["Ownership", "No guessing", "Correct escalation", "Warm transfer", "Follow-up"] },
    ],
  }),
  roleModule({
    id: "cur-support-final-practical",
    slug: "support-final-practical",
    title: "Support Shared Core + Branch Practical",
    summary: "Prove the shared safety/hospitality core, then pass each assigned branch independently.",
    audience: SUPPORT_AUDIENCE,
    minutes: 75,
    outcomes: ["Pass shared core", "Pass selected branch", "Demonstrate consistent performance at 7/30-day audits"],
    prerequisites: ["cur-support-guest-questions-recovery"],
    tags: ["support", "certification", "final-practical", "required"],
    sourceIds: [RESET_SOURCE, TRAINER_SOURCE],
    content: [
      { type: "field-assignment", title: "Certification", prompt: "Complete the shared hospitality, safety, priorities, and handoff proof; then complete the Host, Busser, Food Runner/Expo, or Barback branch practical assigned by leadership.", successCriteria: ["Shared core passes", "Only observed branches are certified", "No critical miss", "7- and 30-day audit scheduled"] },
    ],
    questions: [
      { id: "support-final-knowledge", type: "short-answer", prompt: "Teach back CARE, priorities, safety stops, and closed-loop handoffs.", rubric: ["Accurate", "Observable", "Role boundaries"] },
      { id: "support-final-live", type: "practical", prompt: "Complete shared core and selected branch practical.", rubric: ["Hospitality", "Safety", "Accuracy", "Pace", "Communication", "Branch skill"], critical: true },
    ],
    passingScore: 90,
    criticalMisses: ["Safety/allergy miss", "Wrong certification branch", "Dishonest evidence"],
  }),
] as const satisfies readonly CurriculumModule[];

export const SERVER_ONBOARDING_PROGRAM = {
  id: "program-server-onboarding",
  slug: "server-onboarding",
  title: "Server Onboarding + Certification",
  summary: "Own the table's experience from welcome through farewell.",
  audience: SERVER_AUDIENCE,
  version: "2.0",
  effectiveDate: "2026-08-24",
  moduleIntervalDays: 1,
  moduleIds: SERVER_ONBOARDING_MODULES.map((module) => module.id),
  completionRule: "sequential",
  certification: { knowledgeScore: 90, practicalRequired: true, liveObservationRequired: true, auditDays: [7, 30] },
} as const satisfies CurriculumProgram;

export const BARTENDER_ONBOARDING_PROGRAM = {
  id: "program-bartender-onboarding",
  slug: "bartender-onboarding",
  title: "Bartender Onboarding + Certification",
  summary: "Warm people. Cold drinks. Clean stations. Zero guessing.",
  audience: BARTENDER_AUDIENCE,
  version: "2.0",
  effectiveDate: "2026-08-24",
  moduleIntervalDays: 1,
  moduleIds: BARTENDER_ONBOARDING_MODULES.map((module) => module.id),
  completionRule: "sequential",
  certification: { knowledgeScore: 90, practicalRequired: true, liveObservationRequired: true, auditDays: [7, 30] },
} as const satisfies CurriculumProgram;

export const SUPPORT_ONBOARDING_PROGRAM = {
  id: "program-support-onboarding",
  slug: "support-onboarding",
  title: "Support Staff Onboarding + Certification",
  summary: "Protect welcome, accuracy, pace, cleanliness, and communication underneath the guest experience.",
  audience: SUPPORT_AUDIENCE,
  version: "2.0",
  effectiveDate: "2026-08-24",
  moduleIntervalDays: 1,
  moduleIds: SUPPORT_ONBOARDING_MODULES.map((module) => module.id),
  completionRule: "sequential",
  certification: { knowledgeScore: 90, practicalRequired: true, liveObservationRequired: true, auditDays: [7, 30] },
} as const satisfies CurriculumProgram;
