import { TRAINER_AUDIENCE } from "./audiences";
import type { CurriculumModule, CurriculumProgram } from "./types";

const TRAINER_SOURCES = ["trainer-os-1", "leadership-os-1", "hospitality-reset-2026-08"] as const;

export const TRAINER_OS_MODULES = [
  {
    id: "cur-trainer-identity-selection",
    slug: "trainer-identity-selection",
    title: "Trainer Identity, Selection + Contract",
    summary: "Select culture carriers through evidence, not tenure, speed, popularity, or schedule convenience.",
    audience: TRAINER_AUDIENCE,
    estimatedMinutes: 55,
    outcomes: ["Explain the trainer mission and role boundaries", "Apply the evidence-based selection standard", "Commit to source discipline and honest sign-offs"],
    tags: ["trainer-os", "selection", "required"],
    sourceIds: TRAINER_SOURCES,
    content: [
      { type: "principle", title: "Trainer mission", body: "We do not hand people information. We build capability. Training is hospitality before the guest ever arrives.", tone: "navy" },
      { type: "checklist", title: "Who earns the responsibility", items: ["Role competence under normal volume and pressure", "Culture and hospitality", "Consistency", "Clear communication", "Patience without lowered standards", "Behavioral accountability", "Reliability and source discipline"] },
      { type: "comparison", title: "Trainer vs. leadership", leftLabel: "Certified trainer owns", rightLabel: "Leadership owns", rows: [
        { left: "Prepare the objective and current source", right: "Selection, schedules, materials, bandwidth, and system health" },
        { left: "Demonstrate, create reps, coach, and document evidence", right: "Policy, discipline, accommodations, employment decisions, and final certification authority" },
        { left: "Build independence", right: "Protect enough training bandwidth and resolve source conflicts" },
      ] },
      { type: "standard", title: "The contract", body: "Never teach a hidden shortcut, never invent an answer, never sign off exposure as competency, and never use friendship, comfort, speed, or schedule convenience to certify unproven work.", tone: "orange" },
      { type: "practice", title: "Trainer audition", prompt: "Teach one five-minute current role skill, respond to a planned miss, and complete a short evidence note.", successCriteria: ["Current approved source", "Explains why", "Creates a rep", "Coaches behavior", "No shortcut or guess", "Evidence is specific"] },
    ],
    assessment: {
      passingScore: 90,
      retryLimit: 1,
      practicalRequired: true,
      criticalMisses: ["Teaches a shortcut as the real standard", "Invents a safety or recipe answer", "Signs off unobserved competency"],
      questions: [
        { id: "trainer-identity-1", type: "multiple-choice", prompt: "What qualifies a person to train independently?", options: ["Tenure", "Fast technical performance", "Leadership certification backed by transfer proof", "Popularity with the team"], correctAnswer: "Leadership certification backed by transfer proof" },
        { id: "trainer-identity-practical", type: "practical", prompt: "Complete the five-minute trainer audition.", rubric: ["Culture carrier behavior", "Clear objective", "Current source", "Rep and feedback", "Accurate documentation"], critical: true },
      ],
    },
  },
  {
    id: "cur-trainer-seven-step-method",
    slug: "seven-step-training-method",
    title: "The Seven-Step Training Method",
    summary: "Explain it. Show it. Rehearse it. Use it. Coach it. Prove it. Recheck it.",
    audience: TRAINER_AUDIENCE,
    estimatedMinutes: 70,
    outcomes: ["Use Teach > Demonstrate > Rehearse > Run Live > Coach > Certify > Audit", "Make critical decisions visible", "Separate attendance from evidence"],
    prerequisites: ["cur-trainer-identity-selection"],
    tags: ["trainer-os", "method", "required"],
    sourceIds: TRAINER_SOURCES,
    content: [
      { type: "steps", title: "The method", items: [
        "Teach: explain the purpose, observable standard, approved source, steps, decisions, and stop points.",
        "Demonstrate: perform at normal speed, repeat with slow decision narration, then perform at normal speed again.",
        "Rehearse: create controlled reps away from guest risk; coach one priority and rerun immediately.",
        "Run Live: name the independence level and intervention boundary before the rep.",
        "Coach: use observation, standard, impact, reset, confirmation, and second-take evidence.",
        "Certify: require knowledge, independent performance, and consistency; trainers also require transfer proof.",
        "Audit: recheck on another shift, under pressure, and ideally with another qualified observer.",
      ] },
      { type: "comparison", title: "Demonstration passes", leftLabel: "Pass", rightLabel: "Learner action", rows: [
        { left: "Normal speed", right: "Watch the complete flow and identify what stands out" },
        { left: "Slow narration", right: "Ask questions and name decisions/checkpoints" },
        { left: "Normal speed again", right: "Predict the next decision while the trainer works at service pace" },
      ] },
      { type: "practice", title: "Make thinking visible", prompt: "Teach a current role standard using all seven steps; add one changed condition after the base rep is stable.", successCriteria: ["Objective is narrow", "Source is current", "Decisions are narrated", "Learner completes reps", "Live boundary is explicit", "Evidence and audit are recorded"] },
    ],
    assessment: {
      passingScore: 90,
      retryLimit: 1,
      practicalRequired: true,
      questions: [
        { id: "trainer-method-1", type: "multiple-choice", prompt: "What comes after a coached miss?", options: ["A long explanation", "An immediate second take", "Certification", "A different trainer"], correctAnswer: "An immediate second take" },
        { id: "trainer-method-practical", type: "practical", prompt: "Run the full seven-step loop on an approved task.", rubric: ["Teach", "Three-pass demonstration", "At least two reps", "Safe live level", "Behavioral coaching", "Honest decision", "Audit plan"] },
      ],
    },
  },
  {
    id: "cur-trainer-shift-autonomy",
    slug: "training-shift-autonomy",
    title: "Training Shifts + the Independence Ladder",
    summary: "Schedule training as development, not disguised labor, and transfer ownership in safe stages.",
    audience: TRAINER_AUDIENCE,
    estimatedMinutes: 45,
    outcomes: ["Plan one priority behavior for the shift", "Assign a safe independence level", "Hand off evidence and the next exact rep"],
    prerequisites: ["cur-trainer-seven-step-method"],
    tags: ["trainer-os", "shift-plan", "autonomy", "required"],
    sourceIds: TRAINER_SOURCES,
    content: [
      { type: "standard", title: "Manager protection rule", body: "Do not assign a trainer a normal full workload and expect a complete learning experience on top of it. Schedule the responsibility, name the objective, and protect enough bandwidth to observe.", tone: "warning" },
      { type: "steps", title: "Independence ladder", items: ["Introduced - learner has seen and discussed the standard", "Rehearsed - controlled reps completed with coaching", "Live with direction - trainer provides active cues", "Live with check - learner acts, trainer verifies checkpoints", "Independent certification rep - no coaching unless safety requires intervention", "Certified - evidence meets the role standard", "Audited - behavior survives another shift and observer"] },
      { type: "checklist", title: "Every training shift", items: ["Review prior evidence", "Name one priority objective", "Confirm current source and materials", "State ownership and stop points", "Create base rep, second take, and variation", "Use Keep / Start / Stop", "Document status, evidence, risk, exact next rep, and manager handoff"] },
      { type: "scenario", title: "Volume narrows; it does not erase", prompt: "Volume hits in the middle of a training rep. Safely narrow the trainee's ownership without abandoning the standard or turning them into untrained labor.", successCriteria: ["One task remains owned", "Trainer protects the rest", "Safety boundaries stay explicit", "Decisions are debriefed after the push"] },
    ],
    assessment: {
      passingScore: 90,
      retryLimit: 1,
      practicalRequired: true,
      questions: [
        { id: "trainer-autonomy-1", type: "true-false", prompt: "A training calendar date is enough reason to certify a skill.", correctAnswer: false, explanation: "The calendar schedules opportunity; evidence determines advancement." },
        { id: "trainer-autonomy-practical", type: "practical", prompt: "Plan and lead a training block through a realistic volume spike.", rubric: ["Priority stays narrow", "Safe ownership level", "Trainer does not take over early", "Evidence and next rep documented"] },
      ],
    },
  },
  {
    id: "cur-trainer-coaching-learning",
    slug: "coach-the-rep",
    title: "Coach the Rep, Protect the Person",
    summary: "Use precise evidence, productive struggle, 80/20 questions, and immediate second takes.",
    audience: TRAINER_AUDIENCE,
    estimatedMinutes: 60,
    outcomes: ["Use the 60-Second Coach", "Diagnose clarity, skill, system, environment, or willingness", "Keep questions and honest uncertainty safe"],
    prerequisites: ["cur-trainer-shift-autonomy"],
    tags: ["trainer-os", "coaching", "learning", "required"],
    sourceIds: TRAINER_SOURCES,
    content: [
      { type: "steps", title: "The 60-Second Coach", items: ["Observation - quote behavior, words, timing, or result", "Standard - point to the approved source", "Impact - connect to guest, team, safety, accuracy, pace, or trust", "Reset - give one change for the next rep", "Confirm - learner states the change and reruns"] },
      { type: "script", title: "Difficult moments", lines: [
        "Overwhelmed: 'Tell me the one thing you are trying to control. We will get one clean rep, then add the next piece.'",
        "Defensive: 'I am coaching the behavior I observed. Tell me what you heard the standard to be, then we will rerun.'",
        "Conflicting instructions: 'We are not making you choose between trainers. We will verify the current written standard.'",
        "Trainer unsure: 'I do not want to teach a guess. I will verify and show you where the approved source lives.'",
        "Repeat miss: 'Show me where your process breaks; then we will diagnose clarity, skill, environment, or willingness.'",
      ] },
      { type: "practice", title: "Second-take lab", prompt: "Observe a planned miss, quote facts only, give one reset, and rerun without a speech between reps.", successCriteria: ["No identity labels", "One observable change", "Dignity and urgency protected", "Second take proves whether coaching worked"] },
    ],
    assessment: {
      passingScore: 90,
      retryLimit: 1,
      practicalRequired: true,
      questions: [
        { id: "trainer-coach-1", type: "multiple-choice", prompt: "What proves a coaching conversation worked?", options: ["The trainee says yes", "The trainer explains longer", "The next rep changes", "The manager agrees"], correctAnswer: "The next rep changes" },
        { id: "trainer-coach-practical", type: "practical", prompt: "Coach an overwhelmed trainee, a defensive trainee, and a source conflict.", rubric: ["Reduces load, not standard", "Uses evidence", "Creates next rep", "Verifies source", "Escalates correct owner"] },
      ],
    },
  },
  {
    id: "cur-trainer-four-labs",
    slug: "trainer-development-sprint",
    title: "Two-Week Trainer Development Sprint",
    summary: "Complete four leadership-run labs, progressive co-training, and floor evidence before the practical.",
    audience: TRAINER_AUDIENCE,
    estimatedMinutes: 300,
    outcomes: ["Complete all four 75-minute labs", "Advance through controlled co-training milestones", "Demonstrate transfer under observation"],
    prerequisites: ["cur-trainer-coaching-learning"],
    tags: ["trainer-os", "labs", "co-training", "required"],
    sourceIds: TRAINER_SOURCES,
    content: [
      { type: "steps", title: "Four labs", items: [
        "Lab 1 - What Trainers Teach Without Speaking: identity, operating beliefs, boundaries, contract, and training hospitality.",
        "Lab 2 - Make the Standard Visible: Teach, Demonstrate, Rehearse, and Run Live.",
        "Lab 3 - Coach the Rep, Protect the Person: evidence, 60-Second Coach, 80/20, difficult moments, and second takes.",
        "Lab 4 - Certify, Audit, Improve: honest decisions, documentation, audit, and module repair.",
      ] },
      { type: "steps", title: "Co-training path", items: ["Observe a full training shift", "Own one Teach > Demonstrate > Rehearse module", "Own one live block and evidence note", "Lead a full training shift under observation", "Complete the final practical"] },
      { type: "callout", title: "Do not rush the ladder", body: "A candidate may repeat a milestone. Repetition is not failure; unearned authority is. Advance only when evidence supports the next level.", tone: "sand" },
      { type: "field-assignment", title: "Sprint proof", prompt: "Complete all four lab assignments and four co-training milestones in the recommended two-week sequence.", successCriteria: ["Every candidate performs", "Floor evidence is specific", "No observation-only certification", "Qualified observer approves each advancement"] },
    ],
    assessment: {
      passingScore: 90,
      retryLimit: 0,
      practicalRequired: true,
      questions: [
        { id: "trainer-sprint-1", type: "short-answer", prompt: "Explain the purpose and evidence for each of the four labs.", rubric: ["Identity", "Visible standard", "Coaching", "Certification and system improvement"] },
        { id: "trainer-sprint-practical", type: "practical", prompt: "Complete the four co-training milestones with observer records.", rubric: ["Observe", "Own module", "Own live block", "Lead full shift", "Accurate handoff"] },
      ],
    },
  },
  {
    id: "cur-trainer-certification-audit",
    slug: "certification-audit-calibration",
    title: "Certification, Audit + Calibration",
    summary: "Protect the meaning of trained with knowledge, performance, consistency, transfer, and ongoing recalibration.",
    audience: TRAINER_AUDIENCE,
    estimatedMinutes: 55,
    outcomes: ["Make an evidence-backed certification decision", "Identify critical misses", "Keep trainer status active through audit and calibration"],
    prerequisites: ["cur-trainer-four-labs"],
    tags: ["trainer-os", "certification", "audit", "required"],
    sourceIds: TRAINER_SOURCES,
    content: [
      { type: "comparison", title: "Proofs", leftLabel: "Proof", rightLabel: "Meaning", rows: [
        { left: "Knowledge", right: "Explains why, standard, steps, boundaries, and escalation without reading" },
        { left: "Performance", right: "Executes accurately under realistic conditions without the trainer carrying the result" },
        { left: "Consistency", right: "Behavior survives another shift and pressure" },
        { left: "Transfer - trainer only", right: "Builds the same capability in another person using the full method" },
      ] },
      { type: "checklist", title: "Certification lifecycle", items: ["Pass audition and eligibility", "Complete four labs and floor evidence", "Complete co-training milestones", "Pass final practical at 42/50 or better with no area below 3", "Zero critical safety, accuracy, hospitality, responsible-service, or integrity miss", "Complete 14- and 30-day provisional observations", "Quarterly observed block/calibration", "Annual recertification or equivalent practical", "Re-certify after material changes"] },
      { type: "standard", title: "Pause triggers", body: "Critical miss, dishonest sign-off, repeated drift, culture damage, refusal to calibrate, or inactive status pauses training authority until leadership records the evidence, owner, development step, and review date.", tone: "warning" },
      { type: "practice", title: "Borderline decision", prompt: "Score a mixed performance, compare observers, and defend certify, continue practice, retrain, manager review, or pause using evidence.", successCriteria: ["Independent scores first", "Quotes evidence", "Critical gates applied", "Next step and audit owner recorded"] },
    ],
    assessment: {
      passingScore: 90,
      retryLimit: 1,
      practicalRequired: true,
      criticalMisses: ["Certifies despite a critical miss", "Changes evidence to fit a schedule", "Uses memory instead of the current source"],
      questions: [
        { id: "trainer-cert-1", type: "multiple-choice", prompt: "Which proof is unique to trainer certification?", options: ["Attendance", "Knowledge", "Transfer proof", "Tenure"], correctAnswer: "Transfer proof" },
        { id: "trainer-cert-practical", type: "practical", prompt: "Make and document a borderline certification decision, then plan its audit.", rubric: ["Current rubric", "Accurate evidence", "Critical gates", "Defensible status", "Named audit owner/date"] },
      ],
    },
  },
  {
    id: "cur-trainer-final-practical",
    slug: "trainer-final-practical",
    title: "Trainer Final Practical",
    summary: "Prove you can build capability from plan through audit without ego, shortcuts, or dependence.",
    audience: TRAINER_AUDIENCE,
    estimatedMinutes: 90,
    outcomes: ["Plan and deliver a complete training module", "Coach a planned miss and changed condition", "Make an honest certification decision and audit plan"],
    prerequisites: ["cur-trainer-certification-audit"],
    tags: ["trainer-os", "final-practical", "certification", "required"],
    sourceIds: TRAINER_SOURCES,
    content: [
      { type: "checklist", title: "Practical conditions", items: ["Submit one-page plan one day before", "Use an assigned current standard", "Teach why and standard in under three minutes", "Demonstrate normal / slow / normal", "Create two reps, one coached miss, and one variation", "Set a safe live/pressure boundary", "Use self-assessment and Keep / Start / Stop", "Choose status, document proof, and plan the audit"] },
      { type: "standard", title: "Scoring gate", body: "Passing requires 42/50 or better, no area below 3, and zero critical safety, accuracy, hospitality, responsible-service, or integrity miss.", tone: "orange" },
      { type: "field-assignment", title: "Transfer proof", prompt: "A qualified observer evaluates the candidate on what the learner can now understand and do, not on how impressive the trainer sounds.", successCriteria: ["Plan", "Teach", "Demonstrate", "Rehearse", "Run live/simulate", "Coach/debrief", "Certify/document", "Audit"] },
    ],
    assessment: {
      passingScore: 84,
      retryLimit: 0,
      practicalRequired: true,
      criticalMisses: ["Safety or responsible-service miss", "Recipe/source invention", "Humiliation or culture damage", "Dishonest sign-off"],
      questions: [
        { id: "trainer-final-plan", type: "short-answer", prompt: "Submit the one-page training plan and approved source.", rubric: ["Objective", "Source", "Materials", "Reps", "Live boundary", "Proof and audit"] },
        { id: "trainer-final-live", type: "practical", prompt: "Complete the Trainer Final Practical.", rubric: ["At least 42/50", "No area below 3", "Zero critical miss", "Learner demonstrates transfer", "Documentation complete"], critical: true },
      ],
    },
  },
] as const satisfies readonly CurriculumModule[];

export const TRAINER_OS_PROGRAM = {
  id: "program-trainer-os",
  slug: "trainer-operating-system",
  title: "The Trainer Operating System",
  summary: "Train the trainers. Build culture carriers. Certify the standard.",
  audience: TRAINER_AUDIENCE,
  version: "2.0",
  effectiveDate: "2026-08-01",
  moduleIntervalDays: 2,
  moduleIds: TRAINER_OS_MODULES.map((module) => module.id),
  completionRule: "sequential",
  certification: {
    knowledgeScore: 90,
    practicalRequired: true,
    liveObservationRequired: true,
    auditDays: [14, 30, 90, 365],
  },
} as const satisfies CurriculumProgram;
